### PR TITLE
Improve performance of dns policy

### PR DESCRIPTION
**Pull request by JustinAzoff**
defer allocating various tables until at least 2 pending queries are seen.  Now that most resolvers use dns source port randomization, most connections will only ever see a single outstanding query.

### CODE REVIEW

**Comment by JustinAzoff** [comment]
weird, was not expecting any test failures, but I didn't do the extended tests locally.

**Comment by JustinAzoff** [comment]
Ah, all the failures are multicast dns stuff on port 5353 with a trans_id of 0.   That's definitely not handled the same with my patch.. though I'm not sure if the current baselines are right either.  Can probably fix the tests just by handling trans_id==0 the old way.

**Comment by jsiwek** [comment]
Just as a sanity check: this is a change that potentially breaks user code (the way people need to access `c$dns_state` members changes), but the thinking is that's rare enough and perf. benefit good enough to do that tradeoff ?  (A mechanism in the language that could hide access to record field members might be the best approach if these weren't intended to publicly accessible state, but don't think we have that.)

And the test failure was more for any case where a duplicate transaction ID causes multiple requests to enter the queue: the fix is that when consuming a pending request, the overflow queue needs to pop an element, if available, into the new `c$dns_state$pending_query` member (to maintain the overall queuing order).  E.g. I'll patch like:

```diff
diff --git a/scripts/base/protocols/dns/main.bro b/scripts/base/protocols/dns/main.bro
index fdc08f6c0..3c439fd56 100644
--- a/scripts/base/protocols/dns/main.bro
+++ b/scripts/base/protocols/dns/main.bro
@@ -260,6 +260,12 @@ hook set_session(c: connection, msg: dns_msg, is_query: bool) &priority=5
                        {
                        c$dns = c$dns_state$pending_query;
                        delete c$dns_state$pending_query;
+
+                       if ( c$dns_state?$pending_queries && msg$id in c$dns_state$pending_queries &&
+                            Queue::len(c$dns_state$pending_queries[msg$id]) > 0 )
+                               c$dns_state$pending_query = pop_msg(c$dns_state$pending_queries, msg$id);
+                       else
+                               delete c$dns_state$pending_query;
                        }
                else if (c$dns_state?$pending_queries && msg$id in c$dns_state$pending_queries &&
                     Queue::len(c$dns_state$pending_queries[msg$id]) > 0 )
```

**Comment by JustinAzoff** [comment]
> but the thinking is that's rare enough and perf. benefit good enough to do that tradeoff 

Yeah.. I doubt there are any scripts out there that look at c$dns_state$pending_queries, or even anything under c$dns_state.  Certainly nothing in the package manager or anywhere else on github.

In my tests of replaying 100% dns traffic there is a sizable performance increase with this change.

Popping the next query from the queue makes sense, I thought it might be something like that.

I think the 'else delete c$dns_state$pending_query' in the diff there is redundant?

**Comment by jsiwek** [comment]
> I think the 'else delete c$dns_state$pending_query' in the diff there is redundant?

Oops, yeah, I meant to remove the previous `delete` and have it moved into the `else` branch, thanks.

**Pull request merged**
