### PR TITLE
Add weird for unhandled opcodes in DNS analyzer

### PR DESCRIPTION
**Pull request by timwoj**
This fixes part of #3856. It changes to report a weird for the unhandled opcode instead of a nonsensical one. The sessions still aren't marked as DNS in conn.log.

### CODE REVIEW

**Comment by awelzel** [comment]
Seems m57-long contains NETBIOS over UDP 137 that ended up parsed as DNS with opcodes 5/6. They actually look interesting and include release/registration of hostnames, though we never logged this somewhere properly, just marked it DNS. So this may or may not be better now :man_shrugging:

Here's two pcaps extracted:

[netbios-release-registration-192.168.1.104-137.pcap.gz](https://github.com/user-attachments/files/16688080/netbios-release-registration-192.168.1.104-137.pcap.gz)
[netbios-registration-169.254.225.22-137.pcap.gz](https://github.com/user-attachments/files/16688081/netbios-registration-169.254.225.22-137.pcap.gz)

**Comment by timwoj** [comment]
> Seems m57-long contains NETBIOS over UDP 137 that ended up parsed as DNS with opcodes 5/6. They actually look interesting and include release/registration of hostnames, though we never logged this somewhere properly, just marked it DNS. So this may or may not be better now

Because of course NetBIOS would break things 🤦🏼 

There's nothing in these packets that indicate that this is NetBIOS outside of (1) the port number and (2) the type field in the queries/records blocks being set to `32`. For (2), checking for that won't necessarily work because that value overlaps with other valid values (see footnote [1] in https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4).

**Comment by timwoj** [comment]
I added a check for the NetBIOS port to the interpreter and updated the external tests. A branch of the same name needs to be merged there as well.

**Review by awelzel — COMMENTED** [review]
Left some nits. Were you thinking of closing the associated issue? I'd actually keep it open as this doesn't add DNS UPDATE support (just improves the weirds).

**Comment by timwoj** [comment]
> Left some nits. Were you thinking of closing the associated issue? I'd actually keep it open as this doesn't add DNS UPDATE support (just improves the weirds).

No, I'd leave the issue open until we decide whether to support the other DNS opcodes.

**Review by awelzel — APPROVED** [review]

**Pull request merged**
