### PR TITLE
Fix bug triggered by cloning nested lambdas.

### LINKED ISSUE #725: Nested lambdas don't clone properly.
Running the code below triggers an error `internal error: Attempted to clone an id ('f') with no associated value.`

```zeek
event zeek_init()
        {
        local outer = 100;

        local lambda = function()
        {
                # `f` is detected as an outer id incorrectly.
                local inner = function(a: count, b: count, c: count, d: count, e: count, f: count)
                {
                        print outer + f;
                };
                inner(1, 2, 3, 4, 5, 6);
        };
        lambda();


        local copyLambda = copy(lambda);
        copyLambda();
        }
```

The trouble happens because when `lambda` is created it incorrectly detects `f` as an outer ID and therefore a variable in its closure. 

In the above code the variable `f` has an offset of 5 in `inner`'s frame (its the 6th variable declared - 5th index). So, when `lambda` is cloned, because it has incorrectly decided that `f` is in its closure, it attempts to clone the 6th value in its closure which triggers the error.

Using the variable `a` instead (`print outer + a`) does not cause the error, but likely causes a memory leak as when `lambda` is cloned it will clone the value with offset 0 in its closure twice. Once for `a` and once for `f`.

The solution is likely to modify the logic in `OuterIDBindingFinder` so that it ignores variables which are local to nested lambdas.
https://github.com/zeek/zeek/blob/7b9a27c96a0203e33b46826ad81f489d0b7c1e6c/src/Var.cc#L413-L422

### PR DESCRIPTION
**Pull request by ZekeMedley**
Resolves #725.

Previously, Zeek would leak memory and potentially catch an error if a nested lambda was cloned. This occurred because local variables of nested lambdas were being incorrectly detected as variables in the parent lambdas closure.

This also removes an unneeded check for outer IDs in regular functions that wasn't removed after closures became supported.

I'd appreciate some feedback on how I implemented this. In particular the addition of a new traversal code `TC_SKIPBODY`. That was the most elegant way that I could think of to indicate to inner lambdas that they should skip traversing their bodies, but I understand that adding a new traversal code for that use case only might be less than ideal.

I ran this through leak tests on my machine and it looked fine, but this is my first time using the new system so its possible I missed something there as well.

### CODE REVIEW

**Comment by jsiwek** [comment]
Thanks for taking a look.  Can you rebase or look again starting from what's in `master` ?  This branch doesn't have either new memory error/leak checking stuff or the alternative method of finding outer IDs I was thinking of (which conflicts with this branch):

https://github.com/zeek/zeek/blob/66ca20b7377961266ec2259db173b927057aa1ca/src/Var.cc#L423-L428

That way didn't require any changes to the existing Traversal infrastructure, but toggling `search_inner_lambdas` fails right now and I think that's because I'm not recursively aggregating outer ID references up the lambda chain which now seems more clearly required from the changes in this PR.  And I think that may just be the piece I was missing and understand now that it's needed in order for the name lookups to continue propagating up the closure chain in search of the first Frame that doesn't claim the given ID is "outer" ?

So possibly the change to `master` to make is to have `OuterIDBindingFinder` store a list of inner `LambdaExpr` and then after the Traversal, walk those lambda chains(s) and aggregate the outer IDs as needed.  Don't think the new `TC_SKIPBODY` is necessary and doing another explicit `OuterIDBindingFinder` for the inner lambda seems redundant since it will have already done that Traversal itself?

Also, here's the instructions to build with ASan in case missed:

https://docs.zeek.org/en/latest/devel/contributors/memory-checks.html

**Comment by jsiwek** [comment]
`topic/jsiwek/fix-outer-id-finding` is an alternate branch from `master` to show what I think it equivalent logic, but without changing the basic AST Traversal infrastructure -- it just keeps a stack of `Scope*` as it enters nested lambdas.

@ZekeMedley can you take a look and incorporate that into your branch if it does look equivalent ?  The new btest at least worked for me.  My branch/diff for reference:

https://github.com/zeek/zeek/commit/e90465108a16977de6e17dfff74a7f70e51369b4

**Comment by ZekeMedley** [comment]
That logic does look better :) I'm seeing an error on my end though when I try to run it against the btest. Running that branch on my local machine on the code from the issue:

```zeek
event zeek_init()
        {
        local outer = 100;

        local lambda = function()
        {
                # `f` is detected as an outer id incorrectly.
                local inner = function(a: count, b: count, c: count, d: count, e: count, f: count)
                {
                        print outer + f;
                };
                inner(1, 2, 3, 4, 5, 6);
        };
        lambda();


        local copyLambda = copy(lambda);
        copyLambda();
        }
```

Output:

```
106
106
internal error: Attempted to clone an id ('outer') with no associated value.
```

Is that happening on your end as well, or have I made some sort of mistake getting your branch set up?

**Comment by jsiwek** [comment]
> ```
> 106
> 106
> internal error: Attempted to clone an id ('outer') with no associated value.
> ```
> 
> Is that happening on your end as well, or have I made some sort of mistake getting your branch set up?

Actually I do see that with my branch, but only running like `zeek test.zeek` and not `zeek -b test.zeek`.  Merging your branch into `master` also shows the same behavior.  I pushed a new commit into my branch that will fix it, but ultimately new logic in `master` and the difference in behavior with the `-b` flag I think was just pointing toward a different route of encountering another possible problem with lambdas/closures due to the way the `Frame` for an event is shared across all handlers and reset before executing each body.  You can take this code back to Zeek 3.0 even as an example:

```zeek
global my_func: function();

event zeek_init() &priority=+10
	{
	local outer = 100;

	local lambda = function()
		{
		print outer;
		};

	lambda(); # prints 100
	my_func = lambda;
	my_func(); # prints 100
	}

event zeek_init() &priority=-10
	{
	local qux = 13;
	my_func(); # prints 13, but expected 100 ?
	}
```

```
$ zeek -b test.zeek 
100
100
13
```

That output wasn't what I expected: when the lambda function escapes the scope in which it was created, I'd expect it to freeze the value of anything it was referencing in the enclosing `Frame`.  But here, we see the result the `Frame` being shared across event handler bodies, with `outer` and `qux` sharing the same `Frame` offset and so the lookup of `outer` from within the escaped-lambda just evaluates to that value assigned to `qux` since they're actually just sharing the same `Frame` location.

If I'm right that's not the expected behavior, then can consider treating it as a separate issue, but first idea that comes to mind for that is adding logic in or around the time of `Frame::Reset()` to freeze/clone such closures.

**Comment by ZekeMedley** [comment]
I agree that isn't what we'd expect to see there. I'm also in favor of breaking that out to a separate issue though as it seems external to cloning nested lambdas. I can go ahead and put that together.

For this PR, I went ahead and brought your commits onto this branch. They look good to me and are I prefer that method to the one that I was originally suggesting.

**Comment by jsiwek** [comment]
Cirrus CI looks somehow confused by the complete force-push and isn't running so going to close/re-open and see if it starts running.

**Comment by jsiwek** [comment]
Just moved to #735 and CI started there ok, hope it stays running after I close this...

**Pull request closed without merging**
