### PR TITLE
IntrusivePtr API improvements

### PR DESCRIPTION
**Pull request by MaxKellermann**
Tired of the endless list of memory leaks in Zeek, I thought I'd post some code which puts a systematic end to this kind of code fragility. It's known to be impossible for humans to get raw pointers right, so let the compiler do it for us!

This PR is of course only the beginning, only a demonstration of what can be done. A **lot** of work is necessary to replace all existing `BroObj` pointers with `BroPtr<>`.

Bonus: the last commit fixes a memory leak!

### CODE REVIEW

**Comment by timwoj** [comment]
I didn't look over all of this yet, but have you looked at the intrusive pointer implementation in `IntrusivePtr.h`? How do these changes compare?

**Comment by jsiwek** [comment]
* There's plans for `IntrusivePtr` to gradually take over as either new code is written or we do some updates/bugfixes to existing areas.  Overhauling everything at fast pace could be a task for someone to attempt, though.

* One thing to be mindful of when transitioning is potential API breakages, e.g. for external plugins.  Generally nice to have a deprecation period if we can rather than outright breakages.  We don't have a clear "plugin API" at the moment, so generally hard to know what warrants more care without having a lot of experience (generally most things Val-related I expect to be used frequently in plugins), but one suggestion that would help in that area is trying to organize the changesets so that any bugfixes/leaks that are found as part of the transition get separated out from other unrelated changes as much as possible.  In this case, didn't look too closely yet in this respect, but did notice the leak fix can probably be separated out a bit better for clarity.

* For the leak in `BloomFilterVal::Merge`, yes, good catch.  I believe the `probabilistic::BloomFilter* copy` may also leak on the early-return path immediately before, too.

**Comment by MaxKellermann** [comment]
Duh, there's already a smart pointer implementation! And confusingly, it's called `IntrusivePtr`.
The code is similar (implementing a smart pointer is rather trivial), but there are differences in `IntrusivePtr` which I don't like:
- my class attempts to imitate the C++ standard library as much as possible, to allow a future transition to `std::shared_ptr`, but what I call `release()` (like C++'s `std::unique_ptr`) is called `detach()` in `IntrusivePtr`
- instead of tag classes to choose a constructor at compile time (new reference vs adopt existing reference), `IntrusivePtr` uses a runtime `bool` parameter which is hard to read. I mean, what does `true` or `false` mean here? https://github.com/zeek/zeek/blob/eafcea86d5b9121b1c94d9a6fef9c0d9d9f1d9b0/src/Val.cc#L1987 You have to look it up in the documentation, it's not obvious from calling code; and getting this right is extremely important - getting this stuff right is the whole point of this class. This is how it looks like with my implementation: https://github.com/zeek/zeek/blob/6f145bc587be04da3f39e22e4253a621426a04fc/src/OpaqueVal.cc#L176-L177
- `detach()` has a branch for no reason: https://github.com/zeek/zeek/blob/eafcea86d5b9121b1c94d9a6fef9c0d9d9f1d9b0/src/IntrusivePtr.h#L103-L106 while my code just uses `std::exchange()` without branches: https://github.com/zeek/zeek/blob/6f145bc587be04da3f39e22e4253a621426a04fc/src/Ptr.h#L136
- `IntrusivePtr` has lots of obscure comparison operators, e.g. for comparing raw pointer values, but what's the point of that? https://github.com/zeek/zeek/blob/eafcea86d5b9121b1c94d9a6fef9c0d9d9f1d9b0/src/IntrusivePtr.h#L261-L265

What disappoints me most is that `IntrusivePtr` was merged nearly 4 months ago, but it has not been adopted anywhere after the initial commit. Zeek is full of memory leaks, they're everywhere I look!

**Comment by jsiwek** [comment]
>  confusingly, it's called `IntrusivePtr`.

For history, you might read through the PR that introduced it: #661.  I.e. "intrusive" does have prior usage and meaningful usage here since the reference count is inside the managed object itself, not in the wrapper.

> * my class attempts to imitate the C++ standard library as much as possible, to allow a future transition to `std::shared_ptr`, but what I call `release()` (like C++'s `std::unique_ptr`) is called `detach()` in `IntrusivePtr`

We likely wouldn't transition to `shared_ptr`, but whatever `retain_ptr` becomes standardized as.  Don't know the full history between choice of `detach()` vs. `release()`, maybe upstream proposal originally had `detach()`, but difference seems mostly trivial and could even provide alias if helpful.

> * instead of tag classes to choose a constructor at compile time (new reference vs adopt existing reference), `IntrusivePtr` uses a runtime `bool` parameter which is hard to read. I mean, what does `true` or `false` mean here? 

Mildly agree with boolean arguments in the general sense -- always seems like it warrants separate function or in case of ctor, more desriptive name/tag for easier remembering, but most of time people seem to be alright living with boolean args, so I don't make a fuss.  If you had suggestion for API enhancement of `IntrusivePtr`, feel free to make those.

> * `detach()` has a branch for no reason
>    while my code just uses `std::exchange()` without branches: 

PRs for Implementation improvements also always welcome.

> * `IntrusivePtr` has lots of obscure comparison operators, e.g. for comparing raw pointer values, but what's the point of that? 

I imagine for convenience, to mimic operations you can do with raw pointers, and since other smart pointers like `shared_ptr` also provide similar operators (except maybe not raw pointer comparison operators).

If you can explain why they bother you or what pitfalls you're imagining, that may help.

> What disappoints me most is that `IntrusivePtr` was merged nearly 4 months ago, but it has not been adopted anywhere after the initial commit.

There are a few places after the initial commit which use them.  Like I said, adoption rate so far is based on new or changed code since no one is actively working on a full migration -- and remember most contributors likely have multiple interests/responsibilities in terms of what they help with and simply don't have time to dedicate to this one in particular.  But if you're passionate about driving it forward, that's certainly helpful -- feel free to make a generalize issue/project that others can help decompose/strategize the bigger problem and help contribute to.

**Comment by MaxKellermann** [comment]
I'll edit the commits in this PR to use `IntrusivePtr`.

**Comment by MaxKellermann** [comment]
> If you can explain why they bother you or what pitfalls you're imagining, that may help.

It's undefined behavior, and thus illegal.

**Comment by MaxKellermann** [comment]
As promised, here's my rework of `IntrusivePtr`, and I've rewritten one of the previous patches to use the existing `IntrusivePtr` class.
The `OpaqueVal` patch is postponed until https://github.com/zeek/zeek/pull/802 is merged (because the patch depends on the memleak fix).

**Comment by MaxKellermann** [comment]
> curious what specific contexts a standardized smart pointer like `shared_ptr` had in mind when providing:

That's indeed interesting, I was not aware of these operators - given that they implement unspecified behavior (you're right), it is indeed surprising that this is part of the C++ standard.

cppreference explains: "Having operator< defined for shared_ptr allows shared_ptrs to be used as keys in associative containers, like std::map and std::set"... but what sane person would ever do something like that? Use a shared_ptr as a container key, seriously?

IMHO there is no meaningful application for these operators, and I think it's a mistake that the C++ standard requires those. Not implementing them keeps people from having bad ideas... Robust design makes good ideas easy, and bad/fragile/buggy ideas hard.

**Comment by rsmmr** [comment]
The pointer changes look good to me, too. I like the tags, makes it indeed much more readable. Thanks, Max!

FWIW, I don't see anything wrong with using pointers as container keys. If the instances of a class `T` are compared not by value, but by identity (i.e., address of the instance), then, e.g,., a `set<shared_ptr<T>>` does the right thing.

**Comment by MaxKellermann** [comment]
> If the instances of a class `T` are compared not by value, but by identity (i.e., address of the instance), then, e.g,., a `set<shared_ptr<T>>` does the right thing.

Yes, but that's what I meant when I said "bad/fragile/buggy ideas".

So you have a `set` of pointers, but what's the point of that?
There's one application I could imagine (and it's still a bad idea): you want to have a collection of pointers, and `set` is better than `list` because deletion is `O(log(n))` instead of `O(n)`. But hey, I have `O(1)` for you, and that's `boost::intrusive::list`!
I use `boost::intrusive` containers all the time, because having to do a lookup just because I want to remove an element which I already have a pointer for is so annoyingly inefficient. I hate most of Boost for its unacceptable bloat, but that's a good one.

**Comment by MaxKellermann** [comment]
Rebased with fixup for changes since https://github.com/zeek/zeek/pull/802 was merged and re-added the `OpaqueVal` patch.

**Comment by jsiwek** [comment]
The changes to `OpaqueVal` API now require a bit more planning/thought since those are more likely to see external usage.  For example: https://github.com/J-Gras/bro-fuzzy-hashing.  Currently that plugin is broken for other reasons of not adapting to modern Zeek API, but still demonstrates that we might expect non-zero number of people to rely on the API.

Since it is return types that change here (making potential deprecation path more complex) and still not expecting a huge number of people to be broken by the change, I suggest going ahead with the change with additional/separate steps:

* Add `NEWS` entry on merge to draw more explicit attention to the potential breakage
* Provide a version number that may be used for conditional compilation like #808 suggests (unless I overlooked something already offered for this purpose)

**Comment by MaxKellermann** [comment]
For now, I removed `OpaqueVal` again and I'll resubmit it later, so this PR can be merged without additional delay.

**Pull request merged**
