### PR TITLE
Add new BIF: print_raw()

### PR DESCRIPTION
**Pull request by jsiwek**
zeek-docs need to be generated on merging

Thought behind this is it's a simple workaround we could also include in 3.0.1, mostly just so there's a simpler way to print out valid JSON (as returned by `to_json()`, see #596), but may be generally convenient for cases that would otherwise use `open()` and `enable_raw_output`.

### CODE REVIEW

**Comment by timwoj** [comment]
I'm a little leery to add something like this if you're considering it as a stop-gap measure, because then removing it becomes difficult later if someone uses it. I'd rather just leave it as-is for 3.0.1 since it's not really breaking anyone, and fix it a better way in 3.1.

**Comment by jsiwek** [comment]
I wonder, too.  @rsmmr suggested this since we do currently have an awkward response to "How do I output a valid JSON string containing UTF-8 to stdout in 3.0.x ?".  Answer I came up with would be:

```zeek
local j = to_json("\xc3\xa9");
local f = open("-");
enable_raw_output(f);
print f, j, "\n";
```

With this PR:

```zeek
local j = to_json("\xc3\xa9");
print_raw(j, "\n");
```

After thinking, I do prefer to close this PR without merging since the value of `print_raw` on its own is questionable and there is technically an answer we can give people if needed.  Robin, you fine with closing this?

**Comment by timwoj** [comment]
I agree with just giving people the first one for now.

**Comment by 0xxon** [comment]
I actually kind of like the idea of a print_raw bif. Not specifically because of json, but just because I have encountered a few cases where it would have been useful in the past. (...such as just print-ing binary data that I would have cat-ed to a different file. Admittedly not a common use-case - but still).

**Comment by sethhall** [comment]
Here's how I've always done it before:
    https://github.com/sethhall/bro-junk-drawer/blob/master/game-of-life.bro#L27
and
   https://github.com/sethhall/bro-junk-drawer/blob/master/game-of-life.bro#L52

print_raw sounds more convenient for sure.

**Comment by jsiwek** [comment]
But do we possibly want to wait for a generalized/better way to control printing modes directly in `print` statements?

E.g. these could be a thing (but maybe not final syntax):

```zeek
local s = "...";
print s;    # Default print behavior uses traditional escaping.
print/x, s; # Hex escape everything.
print/u, s; # Don't escape valid UTF-8 sequences.
print/r, s; # Raw printing, don't escape anything.
```

**Comment by 0xxon** [comment]
I don't really see a huge reason to wait - when we come up with a new syntax, we deprecate print_raw, wait a release and remove it. And - the function is not exactly hugely complex - so it won't be a big complexity liability to keep it in for a while.

But - just my opinion.

**Comment by sethhall** [comment]
We already have a solution for printing raw to stdout (my hacky thing I pointed to above).  I think it might make more sense to just aim for the more generalized solution that Jon mentioned since adding print_raw wouldn't immediately solve any problem other than a kind of nasty hack but it could have the side effect of people committing packages to the package repo using the print_raw function.

If there are plans for a better/more generalized mechanism I think we should just do that and skip print_raw.

**Comment by rsmmr** [comment]
Couple notes:

- Regarding the question at hand, I still like the `print_raw()` as a simple version to print out the JSON stuff and avoid the hack. I wouldn't even see this as necessarily just temporary, looks like a BiF that we could just as well keep. That said, I'm not feeling too strong on this, so fine with me either way.

- Regarding a more general solution: I would argue that `print` should simply not escape at all. It should just remove/replace non-printable characters for output-safety, but not attempt to create anything that's reversible. We can leave escaping to other functions instead that have more context (like `to_json` in this case; some generic `escape_string` for other cases; etc ). We'd need to break backwards compatibility of course to do that, so not sure that's a feasible option. Maybe we could transition to a new syntax that comes with new semantics (like `print(...)` as in Python3).

**Comment by 0xxon** [comment]
So - there are a bunch of people who like it and a bunch who think we should wait for a more generalized solution.

I am still tempted to merge this as it is since this is a really minimal addition that does solve an existing problem.

**Comment by jsiwek** [comment]
Didn't seem like strong feelings either way, but since some do like the new BIF a bit more, I'd say go ahead and review+merge.  Even if it's a bit redundant, it's not like it adds significant maintenance burden.

**Comment by 0xxon** [comment]
Will do.

**Pull request merged**
