### PR TITLE
fix for adding a non-managed type to an empty vector

### PR DESCRIPTION
**Pull request by vpax**
A fix for https://github.com/zeek/zeek/issues/1931.

### CODE REVIEW

**Review by 0xxon — APPROVED** [review]

**Comment by 0xxon** [comment]
Vern - do you think we should add a test for this, so that this kind of error does not happen again in the future? If yes - can you do it, or should I do it while merging?

**Comment by vpax** [comment]
> Vern - do you think we should add a test for this, so that this kind of error does not happen again in the future? If yes - can you do it, or should I do it while merging?

@0xxon good thought, I'll get to that in a bit.

**Comment by timwoj** [comment]
This looks like a good candidate to cherry-pick into 4.2 before the final release, since it's fixing a crash and it's pretty self-contained.

**Comment by vpax** [comment]
> This looks like a good candidate to cherry-pick into 4.2 before the final release, since it's fixing a crash and it's pretty self-contained.

Agreed.  It's a quite-simple change so should be stable.  Just added a btest per @0xxon 's suggestion.

**Review by 0xxon — APPROVED** [review]

**Comment by 0xxon** [comment]
@timwoj - are you going to monitor that this should go into 4.2 somehow? Or should I just cherry-pick both commits over into the release branch?

**Comment by timwoj** [comment]
Just as a follow-up, I cherry-picked this into the release branch. It'll be included in 4.2.

**Pull request merged**
