### PR TITLE
GH-323: change builtin plugin namespaces to Zeek

### LINKED ISSUE #323: Zeek renaming: Update Plugin namespace
It'd be good to update anything user-visible relating to plugins so that we avoid breaking stuff there later.

I can think of the following right now:

- The built-in plugins are all in the Bro namespace:

```
# bro -N
Bro::ARP - ARP Parsing (built-in)
Bro::AsciiReader - ASCII input reader (built-in)
...
```

- CMake support is in `BroPlugin`

- The plugin skeleton in aux has various Bro references

### PR DESCRIPTION
**Pull request by jsiwek**
Doing this before 3.0 is nice in terms of removing "Bro" from user-visible places as the plugin namespaces are visible from all the autogenerated script documentation.

Hypothetically, it's a breaking change if maybe someone depends on the output of `-NN` in a unit test or script.  Or possibly they explicitly `@load` one of the generated `.bif` files (which used to have "Bro_" in their name).  I don't see either being too likely.  Any other thoughts on whether changing this could break anything badly?  If not, seems best to get it out of the way now.

(I didn't bother making a branch in `zeek-docs` repo for this, just run the update script if you're merging)

Fixes #323

### CODE REVIEW

**Comment by rsmmr** [comment]
Could let references to the old names keep working? E.g., accept "Bro::SQLiteWriter" as an alias for "Zeek::SQLiteWriter"?

**Comment by rsmmr** [comment]
Otherwise looks good to me.

**Comment by jsiwek** [comment]
> Could let references to the old names keep working? E.g., accept "Bro::SQLiteWriter" as an alias for "Zeek::SQLiteWriter"?

I think it's not needed for the few use-cases here since the namespace change is only for built-in plugins:

* `@load-plugin Bro::ARP`: this a weird usage that people shouldn't be doing since they don't have a say in whether built-in plugins are activated

* `zeek Bro::ARP`: activating via command line is weird in same way as above

* `zeek -N Bro::ARP`: filtering the list of available plugins (dynamic or built-in) would probably only be used in some esoteric scripting to check for presence of a feature, but since these are are built-in, just checking release version number seems better

So I'll merge it as is, but let me know if there's other usages you think of.  Or if there's strong opinions on making those use-cases work, even if a bit odd.

**Comment by rsmmr** [comment]
Yeah, you're right, they are all built-in, so activation shouldn't matter.

**Pull request merged**
