### PR TITLE
Change gzip compression level from 9 to default #614

### PR DESCRIPTION
**Pull request by jcconnell**
First commit to this project. I thought #614 would be a good place to start. I reviewed the documentation for [external contributors](https://www.zeek.org/development/contribute.html) here but some things were unclear. If I made a mistake or any changes should be made, please let me know and I'll fix them right away.

This change replaces `gzip -9` with `gzip` as the default.

### CODE REVIEW

**Comment by 0xxon** [comment]
Hi,
thanks a lot for your contribution :). There is a small problem at the moment - because you kind of encountered a special case.

The commit you made is in a subproject of zeek (in zeekctl). In the zeek repository, the zeekctl directory is only a pointer to the submodule with the commit id (see files changed). You also need to publish your changes to zeekctl somewhere - so clone the zeekctl directory and push your new commit there. At the moment the actual commit that you made is actually not visible to us - the zeekctl pointer now points to a commit ID that is not reachable.

So - please make a fork of the zeekctl repo too and push your commit to zeekctl to that repository. You can either keep this PR open, or directly open a pull request against zeekctl.

If this is unclear in any way, please let me know/comment here :)

**Comment by jcconnell** [comment]
Hello and thank you for your help!

I made a fork of zeekctl, pushed the change to that repository and opened a pull request there. 

How's that?

**Comment by 0xxon** [comment]
Perfect, thanks.

I am going to close this pull request - and will just merge the other one directly into zeekctl.

**Comment by jcconnell** [comment]
Thank you!

**Pull request closed without merging**
