### PR TITLE
Add telemetry API to Zeek

### LINKED ISSUE #1408: Idea: expose Zeek performance metrics to Broker for scraping via Prometheus
Recent Broker versions build on CAF 0.18, which includes support for runtime metrics and can expose them to [Prometheus](https://prometheus.io). On the Broker side, https://github.com/zeek/broker/pull/175 allows users now to spin up the metrics exposition via the environment variable `BROKER_METRICS_PORT`. @timwoj already used a pre-version of that patch to look into Zeek performance with Grafana for the RC2 performance issues.

Feeding performance metrics from Zeek into the backend would give developers, testers and operators access to all-things-performance in one place. @sethhall also mentioned we could (should?) add new BIFs to allow scripts to extend the metrics as well.

Zeek currently has no access to metrics. They are a CAF feature and the metrics registry is part of the actor system. So there are two ways to go about this.

1. We could just expose the actor system from the `broker_mgr`. So far we've avoided tying Zeek directly to CAF APIs, so I have a feeling that's not a preferred solution. 🙂
2. We could wrap the metrics with an opaque Broker or Zeek API and have the `broker_mgr` act as a factory. In code, this would look somewhat like this:
```cpp
// Gauges are available as int64_t and double versions.
auto num_conns = broker_mgr->int_gauge_singleton("zeek", "num-connections", "number of open connections");
// ... when seeing new TCP connections
num_conns.inc();
// ... when seeing FIN
num_conns.dec();

// Option 2.a: Just "hide" the CAF names.
namespace broker { using int_gauge = caf::telemetry::int_gauge; }

// Option 2.b: Hide the CAF internals with a Broker API.
namespace broker {
class int_gauge {
public:
  void inc() noexcept;
  void dec() noexcept;
private:
  void* handle; // needs to cast back to the original type
};
} // namespace broker

// Option 2.c: Completely hide Broker and CAF internals in Zeek.
namespace zeek {
class int_gauge { /* ... similar to 2.b ... */ };
} // namespace zeek
```

A note on the lifetime of the metric objects: once created, CAF stores them in a registry and the pointers to metrics remain valid until the actor system gets destroyed. For Zeek, this would mean the metrics "live" for as long as the Broker Manager lives.

### PR DESCRIPTION
**Pull request by Neverlord**
Closes #1408.

This is not yet the full functionality, but I think integrating feedback on the approach makes sense at this point.

For the most part, the API is a simple wrapper around the CAF metrics API. This API makes use of *spans* (abstraction for contiguous blocks of memory with a pointer and a size). Unfortunately, `std::span` is not yet available to Zeek. This is why I've added a new `Span` class. I could also push this to a detail namespace if preferred, but I figured it may come in handy in other places as well until we can switch to `std::span` instead.

A couple notes on the implementation:
- CAF uses a registry for metrics. Once retrieved, this means metric objects live for as long as the CAF actor system. Hence, CAF hands out raw pointers that an application can safely hang on to. All handle types have an opaque `Impl` member class that Zeek casts to the native CAF types internally.
- Counters and gauges come in two "flavors": `int64_t` or `double`. The former is preferred whenever possible, because integers have more efficient atomic increment/decrement operations on most platforms (like atomic fetch-and-add). A `double` always needs to fall back to compare-and-swap with retry loops. This means there's an `IntCounter` and a `DoubleCounter` with a `Counter<T>` template for convenience (`T` may only be `int64_t` or `double`).
- Handle types have no default constructor. This is to make sure that an application initializes the handles properly before use and we can consequently skip null pointer checking. If this turns out to be too permissive in practice, we can make the handles default-constructable but then we either need to check for null in all member functions or require null checks by the user.
- Unit tests are in `telemetry/Manager.cc`, which hopefully provide a good starting point for seeing how the API works. 🙂
- For technical reasons, we create the telemetry Manager from the Broker Manager.

Once we agree on the general approach, I'll also add:
- [x] [histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) handle types
- [x] BIFs for accessing the metrics API from script land (probably using new `OpaqueVal` classes for wrapping handle types)

### CODE REVIEW

**Review by jsiwek — COMMENTED** [review]
Thanks, so far the test cases are nice and the general approach/structure of the additions LGTM.

Minor note about [Zeek naming style convention](https://github.com/zeek/zeek/wiki/Coding-Style-and-Conventions#function-and-variable-naming) if you feel like changing anything (someone can always clean up just before merging).  Main deviations I noticed were member functions tend to capitalize first `CamelCase` letter and non-member functions go `snake_case` (but sensible to leave `Span` mirroring `std::span` like you did).

**Comment by Neverlord** [comment]
> Thanks, so far the test cases are nice and the general approach/structure of the additions LGTM.
> 
> Minor note about [Zeek naming style convention](https://github.com/zeek/zeek/wiki/Coding-Style-and-Conventions#function-and-variable-naming) if you feel like changing anything (someone can always clean up just before merging). Main deviations I noticed were member functions tend to capitalize first `CamelCase` letter and non-member functions go `snake_case` (but sensible to leave `Span` mirroring `std::span` like you did).

Thanks for the feedback! For some reason, I find it hard to stick to the Zeek coding conventions and I find myself slipping into either Java or CAF coding style. Anyway, should be all cleaned up now (except `Span` for `std::span` compatibility) and I'll start adding the next pieces. 🙂

**Comment by Neverlord** [comment]
Ok, I've got almost all pieces together. The BIF integration feels very verbose to me, so I'm thankful for any feedback to make it more succinct. There's one more C++ type I'd like to add: timers for simplifying time measurements. Essentially that's just porting https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/telemetry/timer.hpp to the Zeek handle types.

Unfortunately, there's one catch with the current code. It requires this CAF patch: https://github.com/actor-framework/actor-framework/pull/1228. The problem is that the Broker manager initializes the actor system in `InitPostScript()`. However, scripts may already access the telemetry API before that point. I fixed it by having a temporary CAF metric registry that then gets merged into the actual registry in `InitPostScript()`. I couldn't find a way to do it without patching CAF. We can't just create the actor system earlier, because the Broker manager reads config parameters from script land to initialize Broker/CAF. Not a big deal, but it means we need to wait on CAF 0.18.1 before we can merge this PR.

**Comment by jsiwek** [comment]
> The BIF integration feels very verbose to me, so I'm thankful for any feedback to make it more succinct.

Some names are a bit long, but I generally wouldn't complain.  Some thoughts/ideas are (1) users could just create shorter aliases themselves if they want (2) workaround lack of function overloading by using Zeek's `any` type in convenience wrapper functions:

```zeek
module Telemetry;
export {
	# Or call it "inc()"
	function increment(val: any): bool
		{
		switch ( val ) {
		case type opaque of int_counter_metric as icm:
			return Telemetry::int_counter_inc(icm);
		case type opaque of dbl_counter_metric as dcm:
			return Telemetry::dbl_counter_inc(dcm);
		case type opaque of int_gauge_metric as igm:
			return Telemetry::int_gauge_inc(igm);
		case type opaque of dbl_gauge_metric as dgm:
			return Telemetry::dbl_gauge_inc(dgm);
		default:
			Reporter::error(fmt("bad Telemetry::increment(%s): wrong type: '%s'",
			                    val, type_name(val)));
			return F;
		}
		}
}
```

Bypassing type-checking with `any` and adding manual casts can get... "sketchy" (especially if you try to add `&default` parameters to the above example), but otherwise may make function names simpler. Also, the above example is implemented as a pure script, not a BIF, meaning even easier for users to add themselves if we just wanted to provide the BIF substrates like you have them.

> Not a big deal, but it means we need to wait on CAF 0.18.1 before we can merge this PR.

Ok, thanks.

**Comment by rsmmr** [comment]
> Also, the above example is implemented as a pure script, not a BIF, meaning even easier for users to add themselves if we just wanted to provide the BIF substrates like you have them.

Yeah, I would suggest we follow what some other frameworks do (including Broker): hide the BiFs by using internal `__XXX` names and then put a pure script framework on top that provides the user API. That way we can untie the API from the BiFs and can make it all a bit nicer (like with those any casts behind the scenes) and also document the API through Zeekygen.

**Comment by rsmmr** [comment]
>  There's one more C++ type I'd like to add: timers for simplifying time measurements. Essentially that's just porting https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/telemetry/timer.hpp to the Zeek handle types.

I'm lacking context here but any chance we could use Zeek's built-in timers for this? That would avoid adding a new class and more importantly it would give us the same notion of time as for the rest of Zeek (i.e., network time driven by packet input).

**Comment by Neverlord** [comment]
Ok, adding a more idiomatic API in script land later sounds like a good idea. I'll prefix the internal names with `__` then. 🙂

> I'm lacking context here but any chance we could use Zeek's built-in timers for this? That would avoid adding a new class and more importantly it would give us the same notion of time as for the rest of Zeek (i.e., network time driven by packet input).

A timer in the metrics API samples the duration of expensive operations. It's just a convenience API that replaces this:

```cpp
auto hdl = ...; // A zeek::telemetry::DblHistogram with unit `seconds`.
auto t0 = std::chrono::steady_clock::now();
expensive_operation();
auto delta = std::chrono::steady_clock::now() - t0;
hdl.observe(duration_cast<duration<double>>(delta).count());
```

with this:

``` cpp
auto hdl = ...;
{
  auto t = zeek::telemetry::Timer{hdl};
  expensive_operation();
}
```

A `Timer` simply stores the current time in its constructor and then adds the elapsed time since construction to the histogram in its destructor.

I'm not sure if there's a use case for metrics that measure time in "Zeek / network time".

**Comment by rsmmr** [comment]
> A `Timer` simply stores the current time in its constructor and then adds the elapsed time since construction to the histogram in its destructor.

Got it, that's a different kind of thing indeed.

**Comment by Neverlord** [comment]
Ok, I've rebased to current `master` for CAF 0.18.2 (thanks for integrating it so quickly, @jsiwek) and added the timer (plus test for it).

I believe @sethhall wanted to add a nice scripting API on top of the BIFs later. 🙂

**Comment by rsmmr** [comment]
I'm wondering if it makes sense to start documenting this in the manual even without the framework in place?

**Comment by jsiwek** [comment]
Didn't think they were critical/necessary to hold up the core Telemetry functionality in this PR, so put the potential follow-up tasks in #1491.

**Pull request merged**
