### PR TITLE
Prep work for Script Compilation: Test Suite updates

### PR DESCRIPTION
**Pull request by vpax**
The bulk of this PR simply shifts a bunch of the tests in the test suite to use statements in `zeek_init()` event handlers rather than global statements.  Doing so makes the test in scope for script compilation/optimization that's based on transforming function/event/hook bodies.  There's also a tweak to adjust a couple of tests that run concurrent Zeek's to load the same script elements, which helps with testing script optimization in ensuring consistent/"balanced" Zeek instances.

### CODE REVIEW

**Comment by jsiwek** [comment]
Is there conceptual reason for not applying script-opt logic to top-level statements that are outside of function-like bodies ?  Would it be simple to create an internal/hidden function composed of the top-level statements, pass it through script-opt machinery the same as other functions, and then call it instead of directly executing top-level statements like it currently does ?

Realize there's probably minimal practical utility in optimizing top-level statements, but seems like maybe an inconsistency/pitfall to want to avoid for niches like writing test-cases or benchmarks/performance-comparisons.

**Comment by vpax** [comment]
I don't think there's any significant hurdle in taking that approach.  It seemed a little weird to me to create a pseudo-function, but I take your point about tests having subtle problems if we go the route of not compiling global statements.  (We have that problem also in another form, because the use of certain constructs like `when` statements currently causes compilation to be skipped.)

Want me to take a run at making this change?

**Comment by jsiwek** [comment]
> Want me to take a run at making this change?

Yeah, if you don't mind and agree it helps at least in the sense of preventing people from mistakenly writing ineffective/inconsistent test cases.

**Comment by vpax** [comment]
Closing out, as this is now superseded by https://github.com/zeek/zeek/pull/1457.

**Pull request closed without merging**
