### PR TITLE
Small Updates to Frame Class

### PR DESCRIPTION
**Pull request by ZekeMedley**
This makes some small updates to Zeek's Frame class.

- Use `size_t` for ID offsets and indexing into a Frame's array. Previously we were using `int`.
- Use `std::unique_ptr<Val*[]>` for Frame's underlying array rather than managing the memory ourselves.
- Use `IntrusivePtr<ID>` for lookups in a frame. Most places where a lookup was being done we  already had an `IntrusivePtr` and were passing its underlying `ID*` into the `SetElement` method.

### CODE REVIEW

**Comment by 0xxon** [comment]
Unassigning myself - since this actually does not currently compile on most supported systems.

@ZekeMedley - can you fix that? :)

**Comment by ZekeMedley** [comment]
Yep :) Looks like non-Mac targets won’t let you have a `unit64_t` and `size_t` version of a method. I tried just using a template but then some casting rules change and baselines fail.

I’ll fix it up after my lecture this evening.

**Comment by jsiwek** [comment]
Another minor comment regarding changing `SetElement()`/`GetElement()` to take `IntrusivePtr<ID>`: those methods don't end up storing the `IntrusivePtr` and we don't expect the `ID` to be deallocated anywhere in the middle of those calls, so it's a bit of wasted cycles doing the +1 and immediate -1 reference count.  Maybe additional overload for convenience is instead the helpful thing to do?  Like:

```c++
Val* GetElement(const ID* id) const;
Val* GetElement(const IntrusivePtr<ID>& id) const
    { return GetElement(id.get()); }
```

**Comment by ZekeMedley** [comment]
@jsiwek that is a great point :) Thanks. I'll add that as well.

**Comment by ZekeMedley** [comment]
Passing now. If anyone has suggestions on a better way to handle the `size_t`vs `uint64_t` issues that I ran into I'd love feedback. Otherwise, Jon's comments are incorporated now and this is probably ready for a final look.

**Comment by JustinAzoff** [comment]
> Use size_t for ID offsets and indexing into a Frame's array. Previously we were using int.

Isn't the frames array storing the local variables for that function?  I feel like we should be making this smaller and we don't actually need to support 18446744073709551615 local variables.

I tried to see if python had a limit.. 1,000,000 worked, but  10,000,000 results in a 246MB .py file and python3 took 20GB to try to parse it before i killed it..

a uint32 is 4,294,967,296 items, we could probably just use a uint16 and if 65k is enough....

**Comment by jsiwek** [comment]
> Isn't the frames array storing the local variables for that function? I feel like we should be making this smaller

Yeah, `uint16_t` would be pretty comfortable (bet we might even get away with `uint8_t`), but unless someone does an actual measurement/benchmark to show what the benefit would be, I'd say leave it be as an `int`.

**Comment by timwoj** [comment]
Not to mention making it bigger breaks the packing work that I just did on Frame 😛

**Comment by ZekeMedley** [comment]
I'm happy to move it back to `int` if that's the consensus. My reasoning for moving to `size_t` was that we're using the value to represent the size of an array. The pedantic way to do that is probably to use an unsigned number as a frame having a "negative" size seems a little strange to me.

What about using `unsigned int` instead? That should keep things sized well and makes more sense semantically to me.

**Comment by jsiwek** [comment]
Yeah, true that a valid size/index/offset would never take on a negative value unless that encodes a special meaning like unknown/uninitialized/error, but think that's expected/common knowledge that shouldn't cause confusion.  If there's a specific example where someone got bit by signed vs. unsigned confusion in this case, that's a good way to justify a change, but without a concrete reason to demonstrate such benefit, it lands more on the side of noisy code churn and worth avoiding.

My suggestions are (1) leave as `int` or (2) change to `uint16_t` if a measurement gets done to show it has non-negligible benefit.

**Comment by ZekeMedley** [comment]
That sounds good to me. I'll fix it up this weekend. Thanks for the input :)

**Comment by timwoj** [comment]
@ZekeMedley ping

**Comment by ZekeMedley** [comment]
I ran into a bunch of build problems that I think have to do with me not understanding how git submodules work which slowed me down a lot. I'll close this for now until finals are over and I get time to dig into it again 👍

**Pull request closed without merging**
