### PR TITLE
ts fields in SMB logs now default to network_time()

### PR DESCRIPTION
**Pull request by sethhall**
This avoids a problem identified by amanbansal2709 in pull
request #1288. I fixed it in a different way than that pull request
by making sure the ts field is always set so that this isssue doesn't
return in the future.

### CODE REVIEW

**Comment by sethhall** [comment]
Ok, I pushed a change to the private suite with the same branch name.  I don't know how to kick off CI here again or even if it's going to pick the right branch there for the Baselines.

**Comment by timwoj** [comment]
> Ok, I pushed a change to the private suite with the same branch name. I don't know how to kick off CI here again or even if it's going to pick the right branch there for the Baselines.

Modify the appropriate commit-hash file in the `testing/external` directory, and CI will kick off a new build.

**Comment by sethhall** [comment]
Huh, I had never looked at how that was implemented.  Thanks though, I'll push that right now

**Comment by jsiwek** [comment]
Thanks, looks like the change in `zeek-testing` commit hash got mixed up with other utf8 stuff you were doing, so I left out doing anything with that repo since every test passed without any change.

**Comment by jsiwek** [comment]
Also, think this can be treated as bug to fix for 4.0.x, let me know if there's reason not to.

**Pull request merged**
