### PR TITLE
Fix HTTP host header handling

### LINKED ISSUE #1844: HTTP HOST Value Bug for IPv6
https://github.com/zeek/zeek/blob/52b3e159a415fb3acd584f95aa64e2d2a9c0b282/scripts/base/protocols/http/main.zeek#L267

If an HTTP request is made directly to an IPv6 address, vs using a domain, the HOST header will look something like this

```
GET / HTTP/1.1
Host: [::1]:8080
```

The referenced line looks for HOSTs that contain a colon and will split on it, returning the first item. If the HOST is an IPv6 address, part of the value will be removed.

The [docs](https://docs.zeek.org/en/master/scripts/base/protocols/http/main.zeek.html#type-HTTP::Info) suggest that the value for this field is the HOST header value unchanged which is not the case. If the line that extracts the HOST could be removed, the IPv6 issue would no longer exist. Otherwise, the pattern could be changed to something like `/:[[:digit:]]{1,5}$/`.

### PR DESCRIPTION
**Pull request by rsmmr**
- Switch to recording unmodified HTTP header. 
- Fix host header normalization in intel framework. 

Closes #1844.

### CODE REVIEW

**Comment by timwoj** [comment]
Is this ready for review?

**Comment by rsmmr** [comment]
Yes, it is!

**Review by timwoj — APPROVED** [review]
This looks good to me. Do you want me to pull it into the next 4.2 RC?

**Comment by rsmmr** [comment]
I would say yes, but will leave it up to you, it is a user-visible change.

**Comment by rsmmr** [comment]
(I'll go ahead and pull it into master either way)

**Comment by rsmmr** [comment]
Merged. Note that I added the NEWS entry for 5.0.0 for now, so if we backport, need to update.

**Comment by timwoj** [comment]
I went ahead and pulled this into 4.2. I'll update NEWS on master.

**Pull request merged**
