### PR TITLE
Bulk baseline update to reflect btest 0.64

### LINKED ISSUE #1307: Update btest baselines for new version
The newer btest versions record canonified baselines. We should do a full update of all baselines before 4.0

### PR DESCRIPTION
**Pull request by ckreibich**
This includes a few canonifier updates to improve the normalized baselines; see the commits for details. It includes bumps of the various submodules with btest baselines, all currently pointing at branches of the same name. These are:

* https://github.com/zeek/paraglob/tree/topic/christian/gh-1307-baseline-refresh
* https://github.com/zeek/zeek-aux/tree/topic/christian/gh-1307-baseline-refresh
* https://github.com/zeek/zeekctl/tree/topic/christian/gh-1307-baseline-refresh
* https://github.com/zeek/trace-summary/tree/topic/christian/gh-1307-baseline-refresh

There's also a corresponding branch for the external testsuite (I finally used it, wheee!):

* https://github.com/zeek/zeek-testing/tree/topic/christian/gh-1307-baseline-refresh

I've reviewed the updated baselines relatively thoroughly ... I think I caught obvious deficiencies in the canonifiers (see above and existing discussion in #1307 ), but it's of course possible I missed something.

I verified that the testsuites still pass on the updated baselines.

Resolves #1307.

### CODE REVIEW

**Comment by 0xxon** [comment]
Just to also add my comment from #1307 here - what is the reason for us doing all the baseline updates at once?

We could just do this and slowly move over to the canonified baseline when a baseline changes, right? Which might make it less probable that we miss something.

**Comment by ckreibich** [comment]
Fwiw, @0xxon ... the idea was that since these baseline updates change the baseline representation quite a bit (with the header & canonification), it's better to do a bulk update that is a no-op in terms test behavior. You could do it over time as well, but if such updates are driven by actual changes to the tests, it would be harder to see those changes.

**Comment by 0xxon** [comment]
@ckreibich - there is a whole bunch of tests that currently fails for me on MacOs (10.15) when calling btest manually in the testing directory.

To give an example:

```
$ ../../auxil/btest/btest -d core.option-errors
[  0%] core.option-errors ... failed
  % 'TEST_DIFF_CANONIFIER=$SCRIPTS/diff-remove-abspath btest-diff .stderr' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  error in /Users/johanna/bro/master/testing/btest/.tmp/core.option-errors/option-errors.zeek, line 4: no type given (testbool)
  == Diff ===============================
  --- /tmp/test-diff.99646..stderr.baseline.tmp	2020-11-30 13:11:21.000000000 +0000
  +++ /tmp/test-diff.99646..stderr.tmp	2020-11-30 13:11:21.000000000 +0000
  @@ -1 +1 @@
  -error in <...>/option-errors.zeek, line 4: no type given (testbool)
  +error in <...>/master/testing/btest/.tmp/core.option-errors/option-errors.zeek, line 4: no type given (testbool)
  =======================================

  % cat .stderr
  error in /Users/johanna/bro/master/testing/btest/.tmp/core.option-errors/option-errors.zeek, line 4: no type given (testbool)

1 of 1 test failed
```

I am not entirely sure why that happens for me - and not for CI.

**Comment by 0xxon** [comment]
This seems to be some disagreement between the different sed versions; installing (and using) gnu sed it works.

For reference, I am using the sed that comes with Mac Os - which does not carry any version identification whatsoever :)

**Comment by 0xxon** [comment]
Ok, that took me a while. \t is not tab on os-x sed, so it matches the letter t. Apparently just inserting a literal tab instead will work; I will try this and then add this to this branch to re-run CI.

**Comment by 0xxon** [comment]
Ok, another one. Any files that have no newlines at the end of the line now seem to be broken, at least on my osx installation.

Example again:

```
$ btest -d bifs.enable_raw_output
[  0%] bifs.enable_raw_output ... failed
  % 'btest-diff output' failed unexpectedly (exit code 1)
  % cat .diag
  == File ===============================
  helloXworldhi== Diff ===============================
  --- /tmp/test-diff.93728.output.baseline.tmp	2020-11-30 13:53:59.000000000 +0000
  +++ /tmp/test-diff.93728.output.tmp	2020-11-30 13:53:59.000000000 +0000
  @@ -1 +1 @@
  -helloXworldhi
  \ No newline at end of file
  +helloXworldhi
  =======================================

  % cat .stderr

1 of 1 test failed
```

It seems that, at least in this case, MacOs is of the opinion that there is a newline at the end of the output file; linux is of the opinion that there is no newline at the end of output file. Changing it to the other makes the test pass on os-x and fail on Linux.

This one I am a bit more stymified about. There was no newline at the end of the original test-file either. The only difference between the old file and the new file seems to be the addition of the comment line at the beginning - which seems to break the comparison on os-x.

Since no canonifiers are used here, this actually looks like a new bug in btest-diff.

**Comment by ckreibich** [comment]
> MacOs is of the opinion that there is a newline at the end of the output file; linux is of the opinion that there is no newline at the end of output file

LOL :-) — thanks for digging into these, Johanna. I'll see if I can find anything.

**Comment by 0xxon** [comment]
Ok, getting there slowly. It turns out that testing/scripts/diff-canonifier outputs a newline to non-newline-terminated files on os-x, and not on linux. This, however, is not new behavior and seems to have been like this for a while; it just now suddenly matters since the canonification is no longer done on the same system as the comparison :)

**Comment by 0xxon** [comment]
...and in what should surprise no one, this is a difference between os-x sed and GNU sed again :)

**Comment by 0xxon** [comment]
Ok, in things that I learned about this. Apparently sed is only supposed to operate on text files - and files that do not have an eol at the end of the file are not seen as text files. So the behavior for this is unspecified.

There seems to be no way to get os-x sed to not emit newlines at the end of the file; the typical suggestion is to use perl instead (which we don't want to do).

I am tempted to just force linux to output a newline at the end of all these tests instead - however, this obviously is also a bit sad, because it would be nice to be able to check that the output files really do not have a newline at the end.

**Comment by 0xxon** [comment]
I think I have a solution to the line end problem. So - next one.  A bunch of tests fail for me on os-x with the following error - and hang forever:

```
[ 66%] scripts.base.frameworks.file-analysis.irc ... failed
  % 'btest-diff thefile' failed unexpectedly (exit code 1)
  % cat .diag
Traceback (most recent call last):
  File "/Users/johanna/bro/btest/btest", line 2542, in <module>
    (succeeded, failed, skipped, unstable, failed_expected) = TestManager(address=addr).run(copy.deepcopy(tests), output_handler)
  File "/Users/johanna/bro/btest/btest", line 340, in run
    self.threadRun(0)
  File "/Users/johanna/bro/btest/btest", line 383, in threadRun
    t.run(self)
  File "/Users/johanna/bro/btest/btest", line 1005, in run
    self.mgr.testFailed(self)
  File "/Users/johanna/bro/btest/btest", line 563, in testFailed
    self._output_handler.testFailed(test, msg)
  File "/Users/johanna/bro/btest/btest", line 1336, in testFailed
    h.testFailed(test, msg)
  File "/Users/johanna/bro/btest/btest", line 1654, in testFailed
    self.showDiag(test)
  File "/Users/johanna/bro/btest/btest", line 1628, in showDiag
    for line in open(f):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 50: invalid start byte
```

**Comment by 0xxon** [comment]
Ok, the reason for this one is that we are btest-diff-ing binary files. And btest is not really 100% ready to deal with binary baselines. This specific instance is not hard to fix, however I am not sure this is the only gotcha with this.

That might be me - but I also feel not super happy about having the btest-comment on top of a binary file - that feels a bit weird.

**Review by 0xxon — CHANGES_REQUESTED** [review]
I think I fixes the problems that prevented the baselines from passing on OS-X.

Someone else should probably take a look at the changes I performed. I am also not a huge fan about the fact that we currently change binary files to include the btest-canonification-headers in them - like e.g. testing/btest/Baseline/scripts.base.frameworks.file-analysis.http.pipeline/3-file (which is a gif)

Perhaps an option for btest-diff telling it that a file is binary, and to not change it would make sense here.

**Comment by ckreibich** [comment]
>  the canonification is no longer done on the same system as the comparison :)

I think this is really the key bit here ... and the fact that this might be problematic hadn't occurred to me. I'd also argue that it _shouldn't_ be problematic. Sigh.

> Perhaps an option for btest-diff telling it that a file is binary, and to not change it would make sense here.

Yeah, for binary files the whole premise of canonification (hopefully) doesn't apply anyway.

Thanks (again) for digging into these. I'll look through your updates shortly.

**Comment by ckreibich** [comment]
I've started with the binary mode support over in zeek/btest#39 and will now go over this branch assuming it. With it, instead of saying
```
@TEST-EXEC env -u TEST_DIFF_CANONIFIER btest-diff extract_files/1
```
you'd just say:
```
@TEST-EXEC btest-diff --binary extract_files/1
```
and the baseline would be left alone.

I'll rebase while I'm at it, too.

**Comment by ckreibich** [comment]
This latest push hopefully covers the controversial binary-file cases. It does pass on FreeBSD for me, and I'm now going to test it on Linux.

Actually, I need to qualify the FreeBSD statement: I noticed that the Zeek testsuite is generally unstable for me on FreeBSD when run parallelized, at least on my 4-core VM. Problems happen mostly in cluster-related tests, roughly one of which seems to fail on each run. I'll dig into that further once the dust on the baselines has settled a bit.

**Comment by ckreibich** [comment]
Okay, I've now gone through and rebased everything. The branches are the same still as posted in the beginning, with an additional one for the private testsuite, which I'd overlooked earlier (thx Johanna):

* https://github.com/zeek/zeek-testing-private/tree/topic/christian/gh-1307-baseline-refresh

Fingers crossed we can merge this time ... :crossed_fingers:

**Comment by 0xxon** [comment]
Ok, I will go through all of this again and try to merge it.

**Comment by 0xxon** [comment]
I am going to merge this in a couple of minutes - with the exception of the zeekctl changes. I am still waiting for the baselines to run here and opened https://github.com/zeek/zeekctl/pull/28

In the future it generally would be great if you could open a PR for each submodule that is touched - even if that is a bit annoying it makes all the tests run :)

**Comment by ckreibich** [comment]
Yay, thanks Johanna. :tada: 

Yeah ... I'm happy to handle these large updates as you prefer. Maybe the first guideline should be to avoid them when feasible... here, seems we could have gone "bottom-up" with PRs for the submodules first. Is that what you mean? It also always makes me nervous to point submodules at my branches, because the merge master needs to update all of these if we use merge commits.

**Comment by jsiwek** [comment]
> It also always makes me nervous to point submodules at my branches, because the merge master needs to update all of these if we use merge commits.

Think it's unavoidable if we want to know how a changeset spanning the full tree of Git submodules behaves under CI before we start merging stuff since it will only get a coherent checkout of the full tree if the submodules are actually changed within the root repo(s) of associated PRs.

**Pull request merged**
