### PR TITLE
Add Zeek script option for metric import topics

### LINKED ISSUE #2343: Support Broker::metrics_import_topics as option
Add support `Broker::metrics_import_topics` so that the metrics export/import can be configured via Zeek scripts only. Currently the import topics can only be set via `BROKER_METRICS_IMPORT_TOPICS`.

Some boiler-plate in Zeek scripts is in the following branch:
https://github.com/zeek/zeek/compare/topic/awelzel/try-broker-metrics-import-topics

@Neverlord - this is what we chatted about, but creating the ticket for tracking now.

### PR DESCRIPTION
**Pull request by Neverlord**
Closes #2343.

---

Requires: https://github.com/zeek/broker/pull/270

### CODE REVIEW

**Comment by awelzel** [comment]
@Neverlord - the baseline for the `plugins.hooks` btest has changed due to the new bif:

https://cirrus-ci.com/task/6100190124834816?logs=test#L136

Would you be up for updating that?

**Comment by awelzel** [comment]
I've tested these changes to enable metrics and centralized import to the manager by default in a cluster setup. So :+1: from me.

**Comment by Neverlord** [comment]
> Would you be up for updating that?

I've updated the baseline. I've also had to update the Baseline for `testing/btest/Baseline/scripts.base.frameworks.telemetry.internal-metrics/out` since it's checking an internal CAF metric. If possible, I think it'd be best to not have baseline for such metrics. How many messages have been processed at that point depends on what CAF and Broker do internally on startup, so it's by no means a stable quantity.

**Comment by awelzel** [comment]
> If possible, I think it'd be best to not have baseline for such metrics. How many messages have been processed at that point depends on what CAF and Broker do internally on startup, so it's by no means a stable quantity.

Agree. I had already skipped the values for histograms representing timings, so could drop the values for the gauge/counters, too. Even just listing them might not be super stable, but that at least provide some visibility into what metrics are being exposed or added.

**Review by 0xxon — APPROVED** [review]

**Comment by ckreibich** [comment]
Should this be covered in https://docs.zeek.org/en/master/frameworks/telemetry.html, or https://github.com/zeek/zeek/wiki/Telemetry? (I'm wondering whether the wiki page should at this point get folded into the docs altogether — thoughts welcome.)

**Pull request merged**
