### PR TITLE
Fix SMB2 response status parsing. Fixes #1286

### LINKED ISSUE #1286: SMB: missing detection of files with multichannel feature enabled
When smb multichannel feature is enabled zeek does not generate smb_files.log, SMB::FileInfo record doesn't contain any value.
The two attached pcap contain almost the same traffic, ransomware-like activity on the same files.

[multichannel.pcap.zip](https://github.com/zeek/zeek/files/5531432/multichannel.pcap.zip)
[no_multichannel.pcap.zip](https://github.com/zeek/zeek/files/5531433/no_multichannel.pcap.zip)

```
@load base/protocols/smb

event smb2_message (c: connection, hdr: SMB2::Header, is_orig: bool)
  {
    print fmt("################# SMB ####################");
    print fmt("command: %s", c$smb_state$current_cmd$command);
    
    if ( c$smb_state?$current_file )
    print "############ CURRENT FILE ################";
    {
      if ( c$smb_state$current_file?$fuid )
        print fmt("fuid: %s", c$smb_state$current_file$fuid);

      if ( c$smb_state$current_file?$path )
        print fmt("path: %s", c$smb_state$current_file$path);

      if ( c$smb_state$current_file?$name )
        print fmt("name: %s", c$smb_state$current_file$name);

      if ( c$smb_state$current_file?$size )
        print fmt("size: %s", c$smb_state$current_file$size);

      if ( c$smb_state$current_file?$action )
        print fmt("action: %s", c$smb_state$current_file$action);
    }
  }
```
diff of output

diff_multichannel

The result is the same with 3.0.11 and 3.2.2.

### PR DESCRIPTION
**Pull request by grigorescu**
There were a few bugs in how we were deciding if an SMB2 response is a fatal vs non-fatal error. Most importantly, the status field was re-used in newer SMB versions for multi-channel support, and it should be ignored in requests. This fix addresses #1286.

There were also some issues in how we were handling the status field in server responses.

### CODE REVIEW

**Comment by 0xxon** [comment]
Would it perhaps be possible to add a testcase that covers this? :)

**Comment by grigorescu** [comment]
> Would it perhaps be possible to add a testcase that covers this? :)

Oops, yes, absolutely. That was my original intent. I'll change this to a draft until it's ready.

I asked the submitter for permission to use their PCAP; if I don't hear back soon, I'll try to create my own setup and PCAP.

**Comment by rsmmr** [comment]
This is on draft still, is it aiming for 4.0?

**Comment by grigorescu** [comment]
Yes, this would be a big feature to get into 4.0, as many of the newer Windows systems use this multi-channel feature by default.

It's now ready.

**Comment by jsiwek** [comment]
Great, thanks Vlad

**Pull request merged**
