### PR TITLE
Logging/cli logdir

### PR DESCRIPTION
**Pull request by kramse**
Hi there

I was looking at the issue #772 and would like to contribute to this.

I have done,
* Analyzed (looked at man pages, and I use Suricata extensively)
Both Snort and Suritcata, two of the most popular IDS engines, use -l for this purpose

* Forked, messed around, created branch, made it work on my machine

I see a small problem when compiling, something about the new Config struct and initialization.

I have NOT done, 
Manual update yet, waiting to see if -l is acceptable as option

Other documentation changes
- but would be happy to help out

Not done any adding of tests, a bit unsure how to proceed

Also unsure about,
supervisor mode - if this does not use the option, I guess nothing needs changes.1

### CODE REVIEW

**Comment by ckreibich** [comment]
Thanks for the contribution, Henrik. Since a significant part of the logging framework configuration happens in scriptland, it would likely be better to keep this ability there as well, similarly to how you can say e.g. `zeek ... LogAscii::use_json=T` in order to switch the logging to JSON. A nice side-effect of this would be that your changes also remain more local to the ASCII writer.

**Comment by kramse** [comment]
Hi Christian, thanks 

So are you suggesting we add this also to the "scriptland"?

Being a teacher doing courses on Suricata and Zeek together and seeing that Snort also has the same option, I would VERY much like to see this feature, command line option added. 

Further about the JSON logging, that is modifying the output format, and few people will remember this unless a Zeek power user. The -l option would be in the manual page and usage instructions, for quick reference.

So to proceed from here,

I was unsure if I should add the environment variable, only added to the usage instructions printed when running the command.
[ ] Remove environment variable - having command line and scriptland would be great.

[ ] Start adding script support for writing to logdir to the logging framework, in a separate branch to keep away from the command line option

**Comment by rsmmr** [comment]
I agree with Christian here on not making this a new command line option. It's really a writer-specific feature where a scriptland option is consistent with how we do it for everything else too. But the environment variable seems fine to me, and we could mention the script-side option inside the variable's summary when print the usage message, if that helps.

**Comment by JustinAzoff** [comment]
there is a `getenv` bif, so it can be implemented in script land and still use an environment variable to change the default.

**Comment by 0xxon** [comment]
I agree with the others about not making this a command-line option - since this is a writer-specific feature. Since this is not going to make it in in like this, I am going to close the PR; if you think that more discussion is helpful, feel free to re-open.

**Pull request closed without merging**
