### PR TITLE
Add a note about the support matrix to .cirrus.yml

### PR DESCRIPTION
**Pull request by 0xxon**
It would be neat to keep the matrix aligned with our CI systems :)

### CODE REVIEW

**Comment by 0xxon** [comment]
Ok, the fact that the sanitizer check failed is kind of interesting (and definitely does not have anything to do with this change :) )

**Comment by Neverlord** [comment]
Hm, looks like Zeek doesn't wait for all threads before exiting `main`. The function `__cxa_finalize` shouldn't get called before everything was shut down properly. I'll look into it.

**Comment by jsiwek** [comment]
I don't know what updating the the support matrix means in terms of the "OBS" column, so may help to describe that in this note: is it "leave it blank and let Johanna sort it out" or "you should also go update the OBS config somewhere", something else?

**Comment by 0xxon** [comment]
I could clarify this more - basically what I meant is just "update the CI column if you change the CI config". OBS has nothing to do with that.

**Comment by 0xxon** [comment]
I updated the wording in the note.

**Pull request merged**
