### PR TITLE
Remove Zeek-side batching of Broker messages

### PR DESCRIPTION
**Pull request by Neverlord**
This PR depends on https://github.com/zeek/broker/pull/64.

The Zeek-side batching was implemented in response to observing performance degradation with Broker compared to the old communication backend. This seems no longer necessary, so we can remove the opaque data as well as the batching messages in Broker.

Instead of serializing into opaque buffers, we simply convert the threading values directly to `broker::data` and vice versa.

FWIW, I also have unit tests for the two new functions `threading_val_to_data` and `data_to_threading_val` locally. Once there is unit testing infrastructure in place (see #643), I'll contribute those as well.

Obviously, this PR severely impacts the behavior of Zeek clusters and shouldn't get merged without further scrutiny and testing. I recorded activity of a locally deployed Zeek cluster after this patch and could replay it with `broker-cluster-benchmark`. So everything *seems* to work on my end.

Before starting to work on this, I used `broker-benchmark` to see whether the Zeek-side batching still has performance benefits. The tool implements three data types it can produce, I only used type 1 (trivial data with short strings) and type 2 (data that mimics `conn.log` entries).

For the first message type, there are still some performance gains from the batching (each bar is one test run with that batch size, i.e., 1 for blue bar [no batching] and then multiplying the batch size by 10 from each bar to the next):

Message Type 1

However, more complex data (as we should expect in an actual deployment) no longer seems to benefit from the batching:

Message Type 2

It seems like there is still optimization potential for small Broker messages, but the benchmark indicates that the Zeek-side batching for real data is no longer necessary to mitigate performance issues in Broker.

As of this PR, we need to constantly convert between `threading::Value` and `broker::data`. I didn't measure the conversion overhead yet, but it requires heap allocations and thus isn't cheap. Dropping `threading::Value` altogether in favor of `broker::data` would most likely increase performance. I'm not sure if that's the next step, though. Seems like we can get larger gains by optimizing serialization and deserialization in Broker/CAF first.

Should further testing reveal issues with this PR, I'm always grateful for test data / guidance. I'm still new to all the `zeekctl deploy` magic. 😉

/edit: updated graphs with correct scaling (previously off by a factor of 10)

### CODE REVIEW

**Comment by Neverlord** [comment]
> I didn't measure the conversion overhead yet, but it requires heap allocations and thus isn't cheap.

Expanding on that, I've implemented a [small benchmark](https://gist.github.com/Neverlord/6b6303e38d1bed00697a48fe1df6f46d) for measuring the overhead of the conversions via `data_to_threading_val` and `threading_val_to_data`.

I've picked `integer`, `string` and `vector` for the performance measurement to have a trivial type, a handle type, and a recursive type. `DataToVal` benchmarks call `data_to_threading_val`, `ValToData` benchmarks call `threading_val_to_data` and `DataToData` simply makes a copy of the Broker data for establishing a baseline.

```
2019-10-21 09:34:42
Running ./build/release/src/zeek
Run on (8 X 2600 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 6291K (x1)
Load Average: 3.28, 3.43, 4.61
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
Messages/DataToVal_integer        85.2 ns         85.1 ns      8168409
Messages/ValToData_integer        13.7 ns         13.7 ns     50976937
Messages/DataToData_integer       8.35 ns         8.34 ns     84364793
Messages/DataToVal_string          235 ns          235 ns      2986183
Messages/ValToData_string          104 ns          104 ns      6725660
Messages/DataToData_string        92.7 ns         92.5 ns      7592932
Messages/DataToVal_vector         1574 ns         1571 ns       432160
Messages/ValToData_vector          392 ns          391 ns      1814388
Messages/DataToData_vector         244 ns          243 ns      2908910
```

Overall, Broker's `variant`-based approach is more efficient and requires less heap allocations (trivial types such as `integer` simply live on the stack, while we always heap-allocate a `threading::Value`). Performance-wise, it seems like a good idea to drop `threading::Value` in favor of a `variant`-based approach. The simple thing would be to just use `broker::data`. If Broker classes should not "leak" to the outside, then we can almost copy & paste `broker::data` into Zeek and should have compatible variant types.

This also implies that rewriting `Val` with a `variant` also reduces overhead in Zeek, but I think that's a much bigger operation).

As an added bonus: a `variant` is much easier to work with and is less prone to misuse.

All that being said, we aren' losing substantial performance as a result of the conversions. The expensive function is `data_to_threading_val`, because `threading::Value` is expensive to create. However, in the current design we have to do the same number of heap allocations when deserializing a batch of `threading::Value` from `serial_data`.

**Comment by rsmmr** [comment]
Yeah, I was about to reply along the same lines. Switching to a variant generally would make sense, but it'd break a bunch of plugins out there, so we'd need to have pretty good reason for going that route.

**Comment by jsiwek** [comment]
Looks like we could potentially remove (or deprecate) the `SerializationFormat` stuff after merging this, though since it's the last usage of `BinarySeralizationFormat` at least in Zeek itself ?  Was that code we planned to get rid of or still technically considered a part of the public `threading::Value` API we need to keep stable?

**Comment by 0xxon** [comment]
I wanted to rip it out last time - the only reason it was kept was broker.

**Comment by 0xxon** [comment]
As another point - generally I am also still curious about the real-world speed of this. There are a bunch of tiny messages that we do exchange via broker (I think sumstats messages can be really small; the same is true for some of the certificate validation stuff, and notices). However I do not have a good feeling how common these are versus log lines - that probably also depends a lot on network traffic.

**Comment by Neverlord** [comment]
> To point out the obvious - threading::value is one part of our API that relatively many external packages interact with

Ok, I didn't know that this API is used by third parties / plugins. For this PR, the question I was primarily looking at is whether we loose performance as a result of using `broker::data` over `threading::Val` in the Broker Manager. This seems not to be the case.

Whether there are potential performance gains for Zeek plugins also depends on how performance-critical these code paths are in the first place—and I cannot speak to that. 🙂

> I wanted to rip it out last time - the only reason it was kept was broker.

I've ripped out the dead code. ✂️

> There are a bunch of tiny messages that we do exchange via broker 

True, but it seems like that has always been the case. At least in the recordings I've played with, Broker sends rather small messages around between the data stores. Removing the "jumbo frames" with this PR should in theory give CAF better opportunities to do its micro batching. But I'm also very curious about real-world performance.

**Comment by Neverlord** [comment]
## Benchmarking Results

A small disclaimer: I've used the initial version of the PR (before the rebase) that passed all tests.

Thanks to @timwoj for providing PCAP recordings and script scaffold for the benchmarking.

After running Zeek with and without the batching, I think we should *not* merge this PR - yet. With the changes, `perf` reports about 15% higher CPU usage on the benchmarking server along with more branch misses. Zeek also took slightly longer to complete the benchmark (183s instead of 176s). The performance is not far off at this point, but it's not negligible either.

On the server, the Zeek logs showed no increase in package drop or other notable degradations. However, the server also has plenty of resources. I did see an increase in package drop on my local machine (2.6 GHz Quad-Core i7) from ~18.5% to ~19.5%. So it seems that the additional tax on the CPU makes a difference at high loads.

In all cases, I've used the default setup from `node.cfg` (logger, manager, one proxy, two workers) and started Zeek using `zeekctl deploy`.

## Communication Overhead

To get a better understanding of what changed at the communication layer, I've recorded two runs and replayed them via `broker-cluster-benchmark` (for this setup, I've had to use the rebased version). Unsurprisingly, the recording for the new version takes more space (46M vs 19M per worker). This is because we only record meta data per message (size and type), so the current Zeek-side batching "compresses" messages by making them opaque to Broker. We would expect the runtime to also increase slightly, because this benchmark does not account for the deserialization Zeek usually performs. However, the runtime doubles from ~10s to ~20s. Again, we'd have to add Zeek's deserialization code to the benchmark to get the full picture, so take this bit with a grain of salt. Still, doubling the runtime is more than what I would've expected. The most likely contributor to the performance degradation is the current overhead in CAF for sending messages.

We've already measured CAF's serializer to Zeek's FMT and it's about 10% slower at the moment. However, removing the Zeek-side batching also increases the amount of CAF messages overall. And the current runtime overhead of CAF messages is [one of the things we're going to address](./build/release/bin/broker-cluster-benchmark -c master.conf) with CAF 0.18. First performance evaluations we did with prototypes of the new messaging design looked promising. Ideally, simply porting Broker to the next CAF release reduces the cost of sending more and smaller messages to a point where it no longer matters for Zeek.

## Next Steps

I would put this PR on hold for now (or close it) and revisit it after CAF 0.18 is out (and after porting Broker to the new version). I feel like digging more into the performance now might be a waste, given that we have already identified issues at the CAF level and started working on it.

**Comment by jsiwek** [comment]
@Neverlord thanks for details, I'll close the PRs for now and opened #771 to track revisiting this after CAF 0.18

**Pull request closed without merging**
