### PR TITLE
Topic/vern/ast dup inlining

### PR DESCRIPTION
**Pull request by vpax**
This branch adds inlining of Zeek scripts.  I've attempted to stack it off of `topic/vern/AST-dup-standalone` (which adds AST duplication), though maybe some git re-jiggering is required to get that to appear cleanly - if so, let me know the right incantations.

The branch adds a single `btest` that's always run (in a new `opt/` subtree), and also a `-a inline` alternative environment for testing against the entire test suite.

There's a small number of places where the code looks forward to additional script optimization changes; these are hard to fully eliminate without risking introducing hard-to-find problems and/or merge headaches when it's time to add those.

### CODE REVIEW

**Comment by vpax** [comment]
Question: I manually resolved the merge conflicts this branch has with `master`, but they're still being reported as in conflict.  Is this because I needed to use `rebase` rather than doing it manually?

**Comment by jsiwek** [comment]
> Question: I manually resolved the merge conflicts this branch has with `master`, but they're still being reported as in conflict. Is this because I needed to use `rebase` rather than doing it manually?

Might be you merged with a local version of `master` that was already slightly outdated ?  I see the conflicts when doing a local merge of latest `master`, too, so seems legit.  Resolving via `merge` versus `rebase` shouldn't matter.

**Comment by vpax** [comment]
Huh the merge complaints are now gone.  Maybe some sort of race condition with the UI (I did refresh this page originally and it still showed the conflicts, but now it doesn't).

**Comment by vpax** [comment]
I've now fixed the merge issues and opened a separate draft PR, https://github.com/zeek/zeek/pull/1303.

**Pull request closed without merging**
