### PR TITLE
Remove uses of bit-fields where fixed types will be more descriptive

### PR DESCRIPTION
**Pull request by timwoj**
This PR removes a number of uses of bit fields where a fixed type such as uint*_t or bool makes the code more readable. It also includes a bit of code modernization work in BroString to remove redundancy.

### CODE REVIEW

**Comment by jsiwek** [comment]
Also generally think it best to avoid using bit-fields unless it's measured to be a Good thing to do in terms of optimization.  Was there a brief sanity check before removing the single-bit bitfields that those aren't actually important memory optimizations?  Maybe also interesting to see if they're actually a performance de-optimization if they make read/writes to those memory locations more expensive.

**Comment by timwoj** [comment]
A 1-bit bitfield with a `uint32_t` will still use 32 bits of memory to store it. That means you can technically stack 32 single-bit fields into that space in memory. Converting those to `bool`, each `bool` will always take a byte of space no matter how you pack them. Effectively this means that if you have less than 4 `bool` flags you're saving space by not using bit fields.

In regards to the changes in this PR, I can see reverting the changes to `Conn` since using bit fields are actually a space savings there. Everything else should either save memory or have no change.

**Comment by timwoj** [comment]
I backed out most of the changes to `Conn`. Here's some quick benchmarks, averaged over 10 runs of 2009-M57-day11-18.trace (`gtime -f "%e\t%M" zeek -r projects/2009-M57-day11-18.trace`):

Master: 6.031   95378.8
With Conn changes: 6.059   96224
Without Conn changes: 6.095   95979.2

**Comment by rsmmr** [comment]
This is ready, right?

**Comment by timwoj** [comment]
Yes, this is ready.

**Pull request merged**
