### PR TITLE
Deprecate stepping-stone analyzer events.

### PR DESCRIPTION
**Pull request by 0xxon**
The analyzer will be removed for 4.1.

Relates to GH-1573

### CODE REVIEW

**Comment by timwoj** [comment]
Generally when something is marked as deprecated, it's deprecated through to the next major version's x.1 release. Are we making a special case for this being immediately removed in 4.1, or should it be deprecated through 5.1 like usual?

**Comment by 0xxon** [comment]
Welll... since this generally looks pretty dysfunctional, we don't want to fix it, and it partially has been marked as deprecated since 2.0 (admittedly in a comment, not in a tag) and no one replied that they are using it when asking on Slack and the mailing list - I kind of am voting to remove it immediately in 4.1, with deprecation warnings added to a 4.0 dot-release.

But I am happy to be told that that is unreasonable.

**Comment by rsmmr** [comment]
> Welll... since this generally looks pretty dysfunctional, we don't want to fix it, and it partially has been marked as deprecated since 2.0 (admittedly in a comment, not in a tag) and no one replied that they are using it when asking on Slack and the mailing list - I kind of am voting to remove it immediately in 4.1, with deprecation warnings added to a 4.0 dot-release.

That sounds good to me. We followed our exception process asking for input, with nobody speaking up for retaining it; and it's indeed in pretty dysfunctional state to begin with. So +1 from me on going ahead.

**Review by timwoj — APPROVED** [review]
`tine` should be `time`, but otherwise looks good.

I'll add this PR to the list for the next 4.0 patch release.

**Comment by 0xxon** [comment]
Thank you. Is it ok for me to merge this into release/4.0 already?

**Comment by timwoj** [comment]
Yep, go for it.

**Comment by 0xxon** [comment]
Cherry-picked to `release/4.0` with comments addressed in 68cdf3fa10b604e0d38f696cd794e49d5d792e94.

**Pull request closed without merging**
