### PR TITLE
Add unit tests to DNS_Mgr

### PR DESCRIPTION
**Pull request by timwoj**
This is technically part of the work for #1635 but it seemed stand-alone enough to merge in ahead of all of that work begin finished. The tests here increase coverage for DNS_Mgr.cc from ~16% to ~80%. It doesn't fully test timeouts and such from `nb_dns` because that relies on the server actually failing to respond in a timely manner. There's one test that's commented out because I don't have ipv6 configured on my network so it fails to connect.

The branch `topic/timw/doctest-2.4.8` in the zeek-3rdparty repo needs to be merged at the same time.

### CODE REVIEW

**Comment by timwoj** [comment]
It looks like Cirrus might be blocking PTR requests from build hosts which is what's causing all of the failures during the build. I asked what's up with that in https://github.com/cirruslabs/cirrus-ci-docs/discussions/958. This PR is on hold until I can get it resolved.

**Comment by timwoj** [comment]
There's some sort of weird interaction going on between the tests. If I run `zeek --test --test-case="dns_mgr default mode"` by hand on one of Cirrus' consoles, the test will pass every time. If I omit the `--test-case` argument, it'll succeed maybe 10% of the time. I'll keep digging at it. I've already considered that it was something about the local DNS cache file zeek creates, and added a call to `unlink` to delete that file before running each test, but that didn't fix it.

I hate to spend a whole lot of time debugging what might turn out to be something weird in the nb_dns code when I'm just going to replace that code soon with c-ares.

**Comment by rsmmr** [comment]
Yeah, how about not merging this for now then, and proceeding with the c-ares work on top. Assuming in the end everything passes, we'll merge all together then (even though I do appreciate you doing the tests first on the existing code!)

**Comment by timwoj** [comment]
Closing this due to conflicts on CI, and not wanting to go down the rabbit hole of debugging nb_dns.

**Pull request closed without merging**
