### PR TITLE
Mask our signal handlers' triggering signals around thread creation

### PR DESCRIPTION
**Pull request by ckreibich**
This addresses the Supervisor-related thread sanitizer complaint in #1500.

I've verified that this produces clean tsan runs on top of @timwoj's `topic/timw/bump-libkqueue` branch when building with clang, including when running parallelized btests.

Minor note: there's an indentation bug after the perftools disabler block starting [here](https://github.com/zeek/zeek/blob/master/src/zeek-setup.cc#L657-L660) — it never unindents through the end of the `setup()` function. Happy to fix that while we're at it. One way to do so is by always using the extra block (which seems safer anyway) and ifdef-protecting only the `HeapLeakChecker::Disabler disabler;` line in it.

### CODE REVIEW

**Review by timwoj — COMMENTED** [review]
The signal changes look good to me.

Regarding the indentation bug, it looks like clang-format isn't handling that bare brace set properly. It shouldn't be indenting it, and then it doesn't know that it should unindent the block following it. Try wrapping the opening/closing braces with `// clang-format {off,on}` and see if that fixes it.

**Comment by ckreibich** [comment]
I tried a few things but am not having much luck. Looks like it indeed doesn't format the parts surrounded by the comment instruction, but it also doesn't take any cues from the disabled part. However, I noticed that when I remove the `#ifdef`s, it unindents as it should, so I think it's getting tripped up by the combo of the `#ifdef` and the block.

When I only remove the first `#ifdef` block (which admittedly is very mean), it gets very huffy and runs for around 15 seconds before indenting the lead-in comment. :-)

**Comment by ckreibich** [comment]
I tweaked the function naming a bit to be more correct.

**Review by 0xxon — APPROVED** [review]

**Comment by timwoj** [comment]
Glad to see this landed. Now to figure out what's still broken in a TSan build.

**Pull request merged**
