### PR TITLE
More deprecation removal for 3.0

### LINKED ISSUE #243: Remove longstanding deprecations
There's deprecated functionality that's been marked as such for a while, but never removed.  Need to consider doing that for 2.7 finally.  Maybe first warrants a policy decision on what length of time to allow before removing deprecations.  My opinion is they should be guaranteed to exist for a single release (and its patch lifecycle).

We need to remove the following:

- [x] All deprecated functions/bifs
- [x] All deprecated events
- [x] `&synchronized` 
- [x] `&persistent`, `.state/state.bst`
- [x] Other deprecated attributes: `&encrypt`, `&mergeable`, `&rotate_interval`, `&rotate_size`
- [x] `&&` and `||` operators for patterns
- [x] BroControl's `update` command
- [x] Communication framework (`RemoteSerializer` and other things linked to that)
- [x] Value serialization
- [x] Potentially: `when` support for watching globals (see #319)
 
To make this possible, we need to add:

- [x] New `clone` implementation (tracked by #293 )

### PR DESCRIPTION
**Pull request by jsiwek**
Merging this should wrap up deprecation removals for 3.0.

`zeek-docs` needs to be updated on merge.

Fixes #243

### CODE REVIEW

**Comment by 0xxon** [comment]
Just a small question before merging this (this one goes mainly to @rsmmr). I think I vaguely remember discussing removing the anonymizer before - and that there was some reason that we might want to keep it.

Do I misremember this - or is there some reason to not throw that out?

**Comment by 0xxon** [comment]
For reference - a list of everything that this removes:
 * gnutella analyzer
 * backdoor analyzer
 * intercon analyzer
 * anonymizer (marked as dysfunctional already)
 * software_version_found & co (apparently never raised)

And a couple of more minor changes.

**Comment by rsmmr** [comment]
- Not quite sure what's broken currently with the anonymizer,  but that seems functionality worth fixing; the BiFs seem quite useful

- backdoor/interconn: I believe I remember an earlier discussion concluding we should leave them in as they remain functional (although essentially unused)

- Gnutella: seems to save remove I'd say

**Comment by 0xxon** [comment]
As one additional comment - I am not really sure I like the change to rotate_packet_dump that much. It seems like the functions used before just allow for more freedom - without many big disadvantages, right?

I am actually kind-of-tempted to just un-deprecate rotate_file_by_name and calc_next_rotate instead.

**Comment by jsiwek** [comment]
> * Not quite sure what's broken currently with the anonymizer,  but that seems functionality worth fixing; the BiFs seem quite useful

Don't know what all is broken, at least lack of IPv6 support.  No opinion on keeping vs. removing -- they were in the "deprecated" section, though, so we should move them if keeping.

> * backdoor/interconn: I believe I remember an earlier discussion concluding we should leave them in as they remain functional (although essentially unused)

No opinion, but all their events are commented as "deprecated", so we should remove that if keeping.

> * software_version_found: Can somebody remind me what happened with these so that they aren't raised anymore?

They've been in an `#if 0` block in the HTTP analyzer ever since we imported into git.

> As one additional comment - I am not really sure I like the change to rotate_packet_dump that much. It seems like the functions used before just allow for more freedom - without many big disadvantages, right?

I wasn't quite sure when you'd want to rotate by name ?  That means you're rotating a file that some other process is creating (why doesn't it do the rotation itself) ?  Otherwise, the only things to rotate in `zeek` would be the `file` type (use `rotate_file`), or the packet dump (would use the new `rotate_packet_dump`).

> I am actually kind-of-tempted to just un-deprecate rotate_file_by_name and calc_next_rotate instead.

I'm fine with doing that instead, too.

Just let me know in general what's all decided here and I'll redo the branch.

**Comment by vpax** [comment]
I think `backdoor` and `interconn` are obsolete at this point.  The former, no longer relevant; the latter, in need of a lot more work to make interesting/robust.

**Comment by jsiwek** [comment]
Sounds like people are ok with the following (complain if you're not):

* Remove `BackDoor`, `InterConn`, and `Gnutella` analyzers

* Un-deprecate `rotate_file_by_name` and `calc_next_rotate`

* Un-deprecate the anonymizer BIFs, still keep marked as not fully functional/tested

* Remove the `software_version_found` event (and related stuff)

**Pull request merged**
