### PR TITLE
Fix segfault with incomplete connection

### PR DESCRIPTION
**Pull request by htonl**
Add required HasField check before GetFieldAs call

### CODE REVIEW

**Comment by htonl** [comment]
This fixes #1601

**Review by timwoj — CHANGES_REQUESTED** [review]
Thanks for the PR. A better solution might be to fix the `GetFieldAs(const char*)` method to check `HasField()` against the index. That would allow the internal error reporting to occur as well. Can you try that and verify that the btests still pass?

Also, it'd be great to add a new btest that covers this case. If you need help with that, let us know and we can guide you through it.

**Comment by htonl** [comment]
Sure, I'll try moving the check to GetFieldAs(const char*). I wasn't sure if the check was not included for performance reasons as per the comments in Val.h (linked below). The comments make it seem like the check was originally left out purposefully, which would mean the path that is taken in this bug is an edge case. I'm happy to try fixing it either way! I'll update the PR tonight with the suggestion.

[https://github.com/zeek/zeek/blob/master/src/Val.h#L1271](url)
[https://github.com/zeek/zeek/blob/master/src/Val.h#L1277](url)

**Comment by timwoj** [comment]
> The comments make it seem like the check was originally left out purposefully, which would mean the path that is taken in this bug is an edge case.

Ah yah, you're right. I forgot we left that out on purpose. What you did seems fine then! Adding a test would be great, then I can merge it.

**Comment by htonl** [comment]
Still working on this, apologies for the delay. Will try to get to the btest soon.

**Comment by htonl** [comment]
Please let me know if I did the btest wrong, or if any further work is needed. Thanks.

**Comment by timwoj** [comment]
The test looks good. I moved it into the `core` section while I was doing the merge.

Thanks again for the fix!

**Pull request merged**
