### PR TITLE
Bump highwayhash to pull in FreeBSD 14 fix

### PR DESCRIPTION
**Pull request by ckreibich**
Upstream has merged @leres's fix for FreeBSD 14, this pulls our build up to include that bump.

### CODE REVIEW

**Comment by leres** [comment]
If you wait for this to [pull request](https://github.com/google/highwayhash/pull/98) to clear, you'll get two FreeBSD fixes for the price of one...

**Comment by 0xxon** [comment]
That one is only for OpenBSD on power though, right? Which is such a rare combination that I think we should not wait for it. Bumping to upstream once they merged that is not a problem in any case.

**Review by 0xxon — APPROVED** [review]

**Comment by leres** [comment]
> That one is only for OpenBSD on power though, right?

I believe it impacts FreeBSD on powerpc64* based on [this commit](https://cgit.freebsd.org/ports/commit/?id=b91d1bd03771d45095637061c58baba5e62fc991) to the FreeBSD security/zeek port.

It's been a couple of weeks so maybe @jasperla isn't going to sign the google CLA. (I'd be happen to re-submit the PR...)

**Comment by 0xxon** [comment]
That PR is different. The one linked above is gated in a way that won't do anything outside of OpenBSD.

**Comment by leres** [comment]
> That patch is different. The one linked above is gated in a way that won't do anything outside of OpenBSD.

Hah, you're right! The FreeBSD and github usernames were similar so I assumed it was the same fix, my bad.

I'll submit an upstream PR for the security/zeek patch @pkubaj committed.

**Comment by leres** [comment]
> I'll submit an upstream PR for the security/zeek patch @pkubaj committed.

I filed the PR and it was accepted and merged (https://github.com/google/highwayhash/pull/101) so it would be nice to do merge the current google/highway has back into zeek.

**Pull request merged**
