### PR TITLE
Improve DNS Analyzer Test Coverage

### PR DESCRIPTION
**Pull request by grigorescu**
Adds some missing tests.

### CODE REVIEW

**Comment by 0xxon** [comment]
Hi Vlad,

I just wanted to check what the state of this is. In general this looks like something that would be great to have in our test suite - and it looks like there should not be much missing :)

**Comment by grigorescu** [comment]
I had started work to get tests for the other DNS types which Zeek currently parses but does not test. Those weren't as straightforward, and I couldn't use an existing DNS host. I got as far as setting up BIND on a system, but haven't had time to circle back.

I can pull this out of draft and get this merged, or leave it until I can complete the work.

**Comment by rsmmr** [comment]
Looks like worth just going ahead and merge I'd say.

**Comment by grigorescu** [comment]
This is ready. For the sake of completeness, I wanted to add a PCAP for the BINDS parsing, which is a private BIND status signaling mechanism. That ended up being a deep rabbit hole, but I did finally manage to get a PCAP of it.

**Review by timwoj — APPROVED** [review]

**Pull request merged**
