### PR TITLE
Add new TCP packet analyzer

### PR DESCRIPTION
**Pull request by timwoj**
This is the third (and final?) in a series of PRs for #1114. This PR moves the TCP analyzer out of the session analysis tree and into the packet analysis framework, building off the work done for the UDP and ICMP analyzers in https://github.com/zeek/zeek/pull/1540.

### CODE REVIEW

**Review by rsmmr — COMMENTED** [review]
Very cool, it's amazing that this restructure actually worked so well!

It's somewhat hard to review because of all the code moving around, but from what I looked at, nothing specific caught my eye. But two high-level thoughts:

- I'm now back to wondering if the SessionAdapters are living at the right place: should we relocate them back into the `analyzers/` tree after all? They are derived from `Analyzer`, and I think what keeps confusing me is that they are doing session-level work/state, vs packet analyzer don't. I think that that would be more intuitive if they were inside the analyzer tree instead. Remind me what the arguments were for putting them into packet_analysis? 

- Along a similar line of thinking, could we move more code out of the TCP packet anlayzer over into the SessionAdapter? I'm thinking a pretty natural boundary could be to have anything that retains state across packets moved over into \ the adapter. For the most part that concerns the TCP_Endpoint management: anything preventing us from doing that inside the adapter instead?

Happy to chat about this as well if that's easier. 

Once we have the final structure in place, I think a diagram & summary of the new architecture and data flow would be really helpful to put together.

**Comment by timwoj** [comment]
That new commit is fixing something related to the last PR that @ckreibich asked me for. I can move it out into it's own PR, but it's all part of the same set of work.

**Comment by ckreibich** [comment]
Just to give the context Tim mentioned above: the ICMP analyzer rework (very reasonably) moved the ICMP-specific flow definition logic into a private method. Community ID relies on this logic to provide hashes when ICMP is involved. The question was whether the re-implement in the Zeek Community ID package, or to keep it available to plugin authors. Since this logic is pretty neat (I haven't seen any other monitors go to such lengths to define flow notions for ICMP), we figured it's worth preserving its access.

**Comment by jsiwek** [comment]
> The question was whether the re-implement in the Zeek Community ID package, or to keep it available to plugin authors. Since this logic is pretty neat (I haven't seen any other monitors go to such lengths to define flow notions for ICMP), we figured it's worth preserving its access.

Preserving access to previously public/stable/user-visible methods (maybe in relation to header file re-organization, too) likely also falls within a general reminder of [backward compatibility](https://github.com/zeek/zeek/wiki/Release-Cadence#backwards-compatibility) promises.  To be consistent with that: either try to avoid breakages (do temporary deprecations, etc.), revise/redact the policy, or explicitly decide/discuss case-by-case when a break may be a preferable tradeoff.

**Comment by timwoj** [comment]
> Preserving access to previously public/stable/user-visible methods (maybe in relation to header file relocation/reorganization, too) likely also falls within a general reminder of backward compatibility promises. To be consistent with that: either try to avoid breakages (do temporary deprecations, etc.), revise/redact the policy, or explicitly decide/discuss case-by-case when a break may be a preferable tradeoff.

Yah, I realize that. I'm debating if this is one of those cases where we spell out that things are broken in NEWS, and let that override the backwards compatibility policy. The one thing that @ckreibich wants fixed is a simple change, but it's still missing adding deprecated headers back into the old locations so that includes work correctly but with a warning.

**Comment by timwoj** [comment]
> Along a similar line of thinking, could we move more code out of the TCP packet anlayzer over into the SessionAdapter?

This should be mostly fixed in https://github.com/zeek/zeek/pull/1566/commits/4982433ef94e6eadadf60da008d48fa991743aca. Apparently those changes broke some of the external tests though so I need to track that down.

> I'm now back to wondering if the SessionAdapters are living at the right place: should we relocate them back into the analyzers/ tree after all?

As we talked about separately, https://github.com/zeek/zeek/pull/1566/commits/534fc1214b6222007645585fd6f13a14ac52ac3c hides the session adapters from `zeek -NN` since they're not truly analyzers. I still have concerns with moving them back over to the session tree. I see the arguments for doing so, but I'm running into a couple questions. Putting them all together in a single directory makes the most sense, including the base class from the IP packet analyzer. Does that directory constitute an actual plugin? If it is a plugin, should it be listed in `zeek -N` or `zeek -NN`? If not, how should the components get registered as analyzers? If they're not registered, a number of the tests break.

**Comment by rsmmr** [comment]
> This should be mostly fixed in [4982433](https://github.com/zeek/zeek/commit/4982433ef94e6eadadf60da008d48fa991743aca). 

I like this, thanks. The TCP packet analyzer is now really small and the flow much easier to understand.

> > I'm now back to wondering if the SessionAdapters are living at the right place: should we relocate them back into the analyzers/ tree after all?

 
> As we talked about separately, [534fc12](https://github.com/zeek/zeek/commit/534fc1214b6222007645585fd6f13a14ac52ac3c) hides the session adapters from `zeek -NN` since they're not truly analyzers.

Looking at the code, we could also keep printing them, but add ` (session adapter)` to the output; that would avoid confusion about what components exist, but still make clear that these are different. What do you think?

> Putting them all together in a single directory makes the most sense, including the base class from the IP packet analyzer. Does that directory constitute an actual plugin? If it is a plugin, should it be listed in `zeek -N` or `zeek -NN`?

Yes and yes, I'd say; it's the "session adapters plugin". That said, if you don't like this, I won't fight too hard: I'm happy with the new split between packet analyzer and adapter, which makes the structure much easier to follow for TCP; if you want to leave the adapters where they are right now, that's fine with me as well.

**Comment by timwoj** [comment]
I changed the output to look like:

```
Zeek::TCP_PKT - Packet analyzer for TCP (built-in)
    [Packet Analyzer] TCP (ANALYZER_TCP)
    [Session Adapter] TCP (enabled)
```

I'm inclined to leave them where they are. It also gives a model for if someone wants to implement one of these in the future by keeping it all together.

**Pull request merged**
