### PR TITLE
Disable script profiling/coverage on sanitizer builds

### PR DESCRIPTION
**Pull request by timwoj**
@ckreibich and I discovered recently that the script coverage/profiling during btest runs causes an awful slowdown on the sanitizer builds, causing them to take about twice as long as they should. For example, running the external tests/m57-long test via btest and running the same test manually:

```
tim@nuc:~/zeek-asan/testing/external/zeek-testing$ /bin/time -f "%e" btest -t tests/m57-long.zeek 
all 1 tests successful
104.05
tim@nuc:~/zeek-asan/testing/external/zeek-testing/.tmp/tests.m57-long$ /bin/time -f "%e" zeek -r ~/test_data/2009-M57-day11-18.trace m57-long.zeek 
47.05
```

But when commenting out the `ZEEK_PROFILER_FILE` option in btest:

```
tim@nuc:~/zeek-asan/testing/external/zeek-testing$ !1997
/bin/time -f "%e" btest -t tests/m57-long.zeek 
all 1 tests successful
49.15
```

This PR adds a little bit of extra code to the `ci/test.sh` file that disables that option for sanitizer builds. The script coverage statistics are still handled by every other build on the CI, but they're not affected by the performance issues because they're not running AddressSanitizer-enabled builds. Currently on master, the sanitizer build takes just over an hour. During testing of this change, it was taking just under 40 minutes.

### CODE REVIEW

**Review by rsmmr — COMMENTED** [review]
Good catch. 

The `sed` might be hard to understand/maintain though. What does Zeek do if the environment variable is set, but empty (`ZEEK_PROFILER_FILE=`). If that worked (i.e., it ignores it), then we could use a btest alternative to just override the value to empty.

(Which reminds me of a long-standing btest feature request of mine: allow an alternative to *delete* an environment variable; I'll create a ticket for.)

**Comment by timwoj** [comment]
> What does Zeek do if the environment variable is set, but empty (ZEEK_PROFILER_FILE=). If that worked (i.e., it ignores it), then we could use a btest alternative to just override the value to empty.

Unfortunately no:

```
tim@nuc:~/zeek-asan/testing/external/zeek-testing$ export ZEEK_PROFILER_FILE=
tim@nuc:~/zeek-asan/testing/external/zeek-testing$ echo $ZEEK_PROFILER_FILE 

tim@nuc:~/zeek-asan/testing/external/zeek-testing$ /bin/time -f "%e" btest -t tests/m57-long.zeek 
all 1 tests successful
105.25
```

**Comment by timwoj** [comment]
Christian and I did discuss whether the profiling should be disabled by default, and only enable it for a few builds on the CI, but it didn't seem to make sense given that we're only running into this problem on the sanitizer builds.

**Comment by rsmmr** [comment]
> Unfortunately no:

Too bad. Then I suggest adding a comment at least to the `sed` command and have it point to https://github.com/zeek/btest/issues/60 to update once we get that.

> 
> ```
> tim@nuc:~/zeek-asan/testing/external/zeek-testing$ export ZEEK_PROFILER_FILE=
> tim@nuc:~/zeek-asan/testing/external/zeek-testing$ echo $ZEEK_PROFILER_FILE 
> 
> tim@nuc:~/zeek-asan/testing/external/zeek-testing$ /bin/time -f "%e" btest -t tests/m57-long.zeek 
> all 1 tests successful
> 105.25
> ```

**Pull request merged**
