### PR TITLE
Support explicit disabling of file analyzers

### PR DESCRIPTION
**Pull request by jsiwek**
Related to https://github.com/zeek/spicy/issues/762

### CODE REVIEW

**Review by rsmmr — APPROVED** [review]
This looks like a straight-forward change with little risk, you think we could still pull that into 4.0?

**Comment by timwoj** [comment]
Do we want to add the risk to the 4.0 release that's already struggling to get out? I know it's a fairly minor change over all but still.

**Comment by jsiwek** [comment]
Not something I'd put in 4.0 -- it's a new feature and we're past the point of feature-freeze.  But if someone finds the potential risk/tradeoff worthwhile enough to deviate from development practices and have ability to carry it into the release branch, they can do what they'd like.

**Comment by rsmmr** [comment]
Alright, I hear you guys. 4.1 it is.

**Comment by ckreibich** [comment]
Seeing that we have plenty of docs work incoming, I'm no longer sure this needs to get covered explicitly. Holler if you think otherwise — thx.

**Pull request merged**
