### PR TITLE
Replace bzero() with memset()

### PR DESCRIPTION
**Pull request by nwt**
This is part of #951.

### CODE REVIEW

**Comment by 0xxon** [comment]
Just for my understanding - and for future documentation:

how does this actually help/what does this change? Because it seems like you are just resolving the existing define for bzero.

Note - I don't have a problem with this change - I am just curious what the motivation is.

**Comment by timwoj** [comment]
This is part of the Windows port, so it's likely that `bzero()` doesn't exist in the mingw headers.

**Comment by nwt** [comment]
@0xxon: I should have either explained what's going on here up front or proposed a narrower change, so please forgive me for not doing that. As @timwoj suggested, bzero() doesn't appear in the MinGW (or MSVC) headers, and that motivates the change to src/Conn.cc, which doesn't see the bzero() macro in src/IntSet.h. The change to src/IntSet.h is strictly housekeeping. Want me to split that into a separate PR or into a separate commit in this PR?

**Comment by timwoj** [comment]
I'm inclined to just take the change like it is. `bzero()`'s been deprecated for a lot of years according to the man page. @0xxon can you think of a system where `bzero()` would be preferred over just using `memset()`?

**Comment by 0xxon** [comment]
Nope, this is fine. I was really entirely only interested in the motivation.

Will merge this in a bit.

**Pull request merged**
