### PR TITLE
Bump Spicy to current `main`.

### PR DESCRIPTION
**Pull request by rsmmr**
This requires a few baseline updates, and a tweak to one test
canonifier.

### CODE REVIEW

**Comment by rsmmr** [comment]
The test failure in the QUIC test showed this in its output:

```
 -1693925959.000001	CHhAvVGS1DHFjwGM9	violation	protocol	QUIC	unhandled QUIC version 0x10010000 (<...>/QUIC.spicy:<line>:<column>)
  +1693925959.000001	CHhAvVGS1DHFjwGM9	violation	protocol	QUIC	unhandled QUIC version 0x10010000 (<...>/QUIC.spicy:280:7-280:57)
```

The location visible there (line 280) is odd, but that's not new: it was reporting the same location before the bump, it was just hidden by the canonification.

**Comment by awelzel** [comment]
Seems this needs and update to the private baselines, too? :-/

**Comment by timwoj** [comment]
I ran into that same Windows build error while working on https://github.com/zeek/zeek/pull/3576. This is building against a fresh rebuild of the docker image, so there's something weird happening with the new version of OpenSSL that gets installed. I wouldn't worry about it for this PR since we don't do Spicy or most of the btests on Windows anyways.

**Comment by timwoj** [comment]
> I ran into that same Windows build error while working on #3576. This is building against a fresh rebuild of the docker image, so there's something weird happening with the new version of OpenSSL that gets installed. I wouldn't worry about it for this PR since we don't do Spicy or most of the btests on Windows anyways.

This is fixed on `master` now if you want to rebase.

**Review by bbannier — APPROVED** [review]

**Pull request merged**
