### PR TITLE
Review for bugprone narrowing conversions changes

### PR DESCRIPTION
**Pull request by devbali**
These are changes that address most of the bugprone narrowing changes warnings given by clang-tidy

### CODE REVIEW

**Comment by jsiwek** [comment]
Didn't look at the changes, but just a quick suggestion to use more descriptive commit messages like "Fix clang-tidy warnings: narrowing conversions".  We roughly follow the style outlined here: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by timwoj** [comment]
> Didn't look at the changes, but just a quick suggestion to use more descriptive commit messages like "Fix clang-tidy warnings: narrowing conversions".

Ideally it'd be broken down by component just to ease reviewing but I realize that it's probably too late to ask for it (and I'm not recommending you go back to fix it now). Something like a commit that is just the changes caused by changing Base64, and so on. Even if it's going to get squashed into a single commit later, it would make reviewing related changes a lot easier.

**Comment by rsmmr** [comment]
What happened to the idea of starting with just a few at first to gauge impact & effort?

**Comment by rsmmr** [comment]
What's the next step here? Should we turn this into a "draft" PR for now?

**Comment by devbali** [comment]
Yeah, I talked to Tim and it seems like a better idea to discard this PR but keep the Branch. I will make PRs for smaller amounts of changes, that are related to each other. Sorry about that.

**Pull request closed without merging**
