### PR TITLE
Build --enable-mobile-ipv6 on CI

### PR DESCRIPTION
**Pull request by timwoj**
Related to #1216. This adds a build on the CI to test the `--enable-mobile-ipv6` configure option and updates the test baselines to properly work with that option.

### CODE REVIEW

**Review by jsiwek — APPROVED** [review]
Thanks, looks fine for at least getting some coverage of that option and since I didn't give an opinion on #1216 yet: if you find there's no/little cost to enabling the option and no egregious flaw/mistake in the associated code that makes it useless to people anyway and there's some certainty it gets coverage via oss-fuzz, I'd remove the configure option and have it always built in.

**Comment by rsmmr** [comment]
I think we should either always enable this, or take out the code. I've been tempted to do the latter unless there was clear evidence that people are using this in practice, but I'm also fine with leaving it in if we do at least a quick code review and then watch for oss-fuzz reports.

**Comment by timwoj** [comment]
I'm going to go ahead and merge this as-is, and fix oss-fuzz to use the option. Then we can set a timeline for just enabling it all the time if there aren't any findings there. Does that sound reasonable?

**Comment by rsmmr** [comment]
> I'm going to go ahead and merge this as-is, and fix oss-fuzz to use the option. Then we can set a timeline for just enabling it all the time if there aren't any findings there. Does that sound reasonable?

Yeah, as long as we will fully enable it some substantial time before the next release so that we have some people buillding/using it during this development phase too.

**Pull request merged**
