### PR TITLE
Add fuzzing support

### PR DESCRIPTION
**Pull request by jsiwek**
Relates to #915

Opening a draft for any early feedback.  See README for examples.  The last task I have planned is modifying our CI to run fuzzers through the ASan build (quick check for regressions and just make sure the fuzzers still build/work).

The next step after merging this would be to get the our project added to OSS-Fuzz.  The branch I have ready for that is here: https://github.com/google/oss-fuzz/compare/master...jsiwek:add-zeek (to test before this PR gets merged, just add a `--branch=topic/jsiwek/fuzzing` to `Dockerfile`)

### CODE REVIEW

**Comment by JustinAzoff** [comment]
I was able to use the 'testing locally' process and can verify everything works perfectly.  I even tried with --engine=afl and that just worked too.

For CI they offer a github integration that we might be able to take advantage of: 
https://google.github.io/oss-fuzz/getting-started/continuous-integration/

I could see the 'one target' per analyzer being a problem, since currently we are at

```244M    build/out/zeek/zeek-pop3-fuzzer```

If we add 40 of those.. that might get too large:

> In addition, please keep the size of the build (everything copied to $OUT) small (<10GB uncompressed). The build is repeatedly transferred and unzipped during fuzzing and runs on VMs with limited disk space.

Maybe a multicall binary with symlinks would work, but I don't know if oss-fuzz tools would accept that.

**Comment by JustinAzoff** [comment]
One thing I've been thinking is if the buffer splitter code should malloc a new buffer for each chunk, before passing it to the analyzer.  That way if DeliverStream ends up reading past the end of an earlier packet asan will detect it.

**Comment by jsiwek** [comment]
> For CI they offer a github integration that we might be able to take advantage of:
> https://google.github.io/oss-fuzz/getting-started/continuous-integration/

Yeah saw that, but think it's more specifically for testing PRs (and can look into it more after the first step of getting the OSS-Fuzz project running).

> I could see the 'one target' per analyzer being a problem, since currently we are at
> 
> `244M build/out/zeek/zeek-pop3-fuzzer`
> 
> If we add 40 of those.. that might get too large:
> 
> > In addition, please keep the size of the build (everything copied to $OUT) small (<10GB

Yeah, I'll do a quick experiment to see if I can reduce the binary sizes (e.g. use shared lib for objects the fuzzers will have in common).

> Maybe a multicall binary with symlinks would work, but I don't know if oss-fuzz tools would accept that.

Not too sure either, and also think it's generally a bit premature to consider -- don't have a clear idea of what customization of the setup/cleanup code each fuzzer will need so don't want to try to factor out a commonality yet.

> One thing I've been thinking is if the buffer splitter code should malloc a new buffer for each chunk, before passing it to the analyzer. That way if DeliverStream ends up reading past the end of an earlier packet asan will detect it.

Great point, I'll change it to do that.

**Comment by jsiwek** [comment]
This is ready for review/merge.  The next steps after that, in order, are:

* Request addition of Zeek project to OSS-Fuzz (#915 is done at that point).  That's this branch: https://github.com/google/oss-fuzz/compare/master...jsiwek:add-zeek
* Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) to extending fuzzing to cover PRs

We can also add fuzzers for more components at any time.

**Comment by JustinAzoff** [comment]
I re-ran through the

```
infra/helper.py build_fuzzers zeek
infra/helper.py check_build zeek
infra/helper.py run_fuzzer zeek zeek-pop3-fuzzer
```

and everything still works great.

**Comment by JustinAzoff** [comment]
Found one small issue:

```
$ ./build/src/fuzzers/zeek-pop3-fuzzer thisfiledoesnotexist
Standalone fuzzer processing 1 inputs
  thisfiledoesnotexist:AddressSanitizer:DEADLYSIGNAL
=================================================================
==35735==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f8fce6f9e53 bp 0x000000000000 sp 0x7ffed3dd3230 T0)
==35735==The signal is caused by a READ memory access.
==35735==Hint: address points to the zero page.
    #0 0x7f8fce6f9e52 in fseek (/nix/store/6m2k8kx8h216jlx9dg3lp4m90bz05yck-glibc-2.30/lib/libc.so.6+0x77e52)
    #1 0x4fdd98 in main /home/justin/src/zeek/build/../src/fuzzers/standalone-driver.cc:31:3
    #2 0x7f8fce6a5d8a in __libc_start_main (/nix/store/6m2k8kx8h216jlx9dg3lp4m90bz05yck-glibc-2.30/lib/libc.so.6+0x23d8a)
    #3 0x420f99 in _start /build/glibc-2.30/csu/../sysdeps/x86_64/start.S:120
```

**Comment by JustinAzoff** [comment]
hmm, there might be a problem with the linking.. I just rebuilt with ```./configure --enable-fuzzers --sanitizers=address,fuzzer-no-link```

but it's not using libuzzers main:

```
./build/src/fuzzers/zeek-pop3-fuzzer -help=1
Standalone fuzzer processing 1 inputs
```

The oss_fuzz scripts seem to still work, but it's running really slowly:

```
#32	pulse  cov: 6176 ft: 8111 corp: 16/105b exec/s: 8 rss: 269Mb
#64	pulse  cov: 6226 ft: 8607 corp: 32/243b exec/s: 8 rss: 269Mb
#128	pulse  cov: 6328 ft: 9755 corp: 62/612b exec/s: 7 rss: 270Mb
#256	pulse  cov: 6723 ft: 12154 corp: 114/1829b exec/s: 6 rss: 272Mb
#512	pulse  cov: 7329 ft: 15805 corp: 225/7330b exec/s: 6 rss: 272Mb
```

**Comment by JustinAzoff** [comment]
gah, nevermind...  i see you have in the README now that one should use

```
LIB_FUZZING_ENGINE=""  ./configure ...
```

**Comment by jsiwek** [comment]
> LIB_FUZZING_ENGINE=""  ./configure ...

Yeah, without that, it builds the "standalone" fuzzer driver, i.e. not being driven by any fuzzing engine.  It's mostly for use with our own CI to ensure the fuzz targets remain in a basically-functional state.

> The oss_fuzz scripts seem to still work, but it's running really slowly:

Don't think that's on our end.  Can manually get a shell and run the fuzzer without corpus to see it iterate faster.  Then having it use the seed corpus, it only starts out that slow for several minutes and picks up speed (guessing some detail of the fuzzing engine initialization process).

**Comment by JustinAzoff** [comment]
weird.. yeah, the initial corpus is just processed really slowly:

```
Running: ./c/670d8bdc32090b27f88c86750e6b0b39578bfd61
Executed ./c/670d8bdc32090b27f88c86750e6b0b39578bfd61 in 371 ms
Running: ./c/675420e9ff81037066e0543136675531698320bf
Executed ./c/675420e9ff81037066e0543136675531698320bf in 357 ms
Running: ./c/6818ca6de0413d410c874ce9250a83738c7df2a4
Executed ./c/6818ca6de0413d410c874ce9250a83738c7df2a4 in 345 ms
```

But running the same corpus through the standalone driver processes the entire corpus in half a second... 
with asan enabled that only grows to 2.5s,  so it's not our fuzzing code that's slow...

it even seems like the libfuzzer main itself is just slower now for some reason:

```
$ time  ./zeek-pop3-fuzzer -help=1 2> /dev/null
real	0m4.239s
user	0m4.004s
sys	0m0.247s
```

I need to re-build an older commit  to verify,  but I don't remember -help=1 taking 4 seconds before.  I wonder if something with the  dynamic linking made everything slower?

**Comment by JustinAzoff** [comment]
ah, so it's not anything we  are doing..

I did

```
$ python3 infra/helper.py shell zeek
$ LIB_FUZZING_ENGINE='' CC=clang CXX=clang++ ./configure --enable-fuzzers --sanitizers=address,fuzzer-no-link --disable-python --disable-zeekctl --generator=Ninja  && time ninja -C build
```
and that is fast...

```
$ time ./build/src/fuzzers/zeek-pop3-fuzzer -help=1 2>/dev/null
real	0m2.048s

Running: ./c/0090d6ea69c4e49a979692cc88633f70d8a03d04
Executed ./c/0090d6ea69c4e49a979692cc88633f70d8a03d04 in 2 ms
Running: ./c/0156cade8c8bb80cf77981a5c47d394559101b7e
Executed ./c/0156cade8c8bb80cf77981a5c47d394559101b7e in 5 ms
Running: ./c/020eaeaa32a408327db915c5d370e0f4cb45752b
Executed ./c/020eaeaa32a408327db915c5d370e0f4cb45752b in 7 ms
Running: ./c/0224500d9444a2aa7146954a016319955292e1c6
Executed ./c/0224500d9444a2aa7146954a016319955292e1c6 in 2 ms
Running: ./c/0251a32c850fbf9a1408a19885bd0a7732b046e9
Executed ./c/0251a32c850fbf9a1408a19885bd0a7732b046e9 in 1 ms
Running: ./c/032e673ec1b81364a0d433d9c3c1e829151d37b1
```

Somehow the binary that `infra/helper.py build_fuzzers` builds is much slower... I bet the version of libfuzzer they are linking in is older/newer and has an issue somewhere..

**Comment by JustinAzoff** [comment]
The latest commit is failing to build for me with

```
../src/fuzzers/standalone-driver.cc:33:50: error: use of undeclared identifier 'errno'
                        printf(" failed to open file: %s\n", strerror(errno));
```

**Comment by JustinAzoff** [comment]
Tracked  down the performance difference.  The detect_leaks=1 feature in the oss-fuzz libfuzzer is disabling itself much slower than in the manual builds.  If you force detect_leaks=0 then the performance is identical.  I'm not sure what is causing THAT difference, but there's at least no fuzzing performance regression in the oss-fuzz environment that we should  be concerned about.

**Comment by JustinAzoff** [comment]
I updated my packet based fuzzer and got it working with the new branch(so much easier now!)  It's in topic/jazoff/fuzzing-plus-packet if you want to add it to this PR or we can always merge it later.

**Comment by JustinAzoff** [comment]
I just hit an interesting issue with that new packet fuzzer which might affect other fuzzers.  It got into an infinite loop when calling zeek::fuzz_cleanup_one_input in DNS_Analyzer::ExpireTimer because nothing was moving time forward.  I fixed it by setting terminating = true before calling the cleanup function, and setting it to false at the top.

**Pull request merged**
