### PR TITLE
FreeBSD: don't look for jemalloc as a package, it's in the base system

### PR DESCRIPTION
**Pull request by leres**
Aashish  was having trouble building 4.1.0 under FreeBSD with jemalloc support enabled and was getting an error:

> -- Could NOT find JeMalloc (missing: JEMALLOC_LIBRARIES JEMALLOC_INCLUDE_DIR)
> CMake Error at CMakeLists.txt:297 (message):
> Could not find requested JeMalloc
> 

The problem here is that jemalloc is included in the base system (see JEMALLOC(3)). This appears to be a standard problem; the fix suggested here:

> https://jira.mariadb.org/browse/MDEV-22975

is to not do a cmake package search.

I've  tested this change on 4.1.0 but not with master.

### CODE REVIEW

**Comment by timwoj** [comment]
You might need to at least set JEMALLOC_FOUND there, or the output from `configure` says that it wasn't found. See https://api.cirrus-ci.com/v1/task/6005732895096832/logs/build.log for example.

**Comment by leres** [comment]
> You might need to at least set JEMALLOC_FOUND there, or the output from `configure` says that it wasn't found. See https://api.cirrus-ci.com/v1/task/6005732895096832/logs/build.log for example.

Good idea, I've updated.

**Review by timwoj — APPROVED** [review]
Looks good to me. Turns out that the variable doesn't need to be set (I was looking at a build without the argument passed). It doesn't hurt anything for it to be set now though so just leave that commit.

Part of me wonders if we should make the output from `configure` state something to the effect that jemalloc is always enabled on FreeBSD instead of letting it say false unless you provide the argument. It's up to you whether you want to add that to this. Otherwise I can make a ticket and someone can pick it up later.

**Comment by leres** [comment]
> Looks good to me. Turns out that the variable doesn't need to be set (I was looking at a build without the argument passed). It doesn't hurt anything for it to be set now though so just leave that commit.
> 
> Part of me wonders if we should make the output from `configure` state something to the effect that jemalloc is always enabled on FreeBSD instead of letting it say false unless you provide the argument. It's up to you whether you want to add that to this. Otherwise I can make a ticket and someone can pick it up later.

I think a problem with my current  set of changes is there's no way to use an alternative jemalloc; for example if you want to build jemalloc with options that the base system does not enable. So please let me take another shot at the changes before merging.

**Comment by timwoj** [comment]
> I think a problem with my current set of changes is there's no way to use an alternative jemalloc; for example if you want to build jemalloc with options that the base system does not enable. So please let me take another shot at the changes before merging.

Sounds good. Just ping me when you're ready for another review.

**Comment by leres** [comment]
> I think a problem with my current set of changes is there's no way to use an alternative jemalloc; for example if you want to build jemalloc with options that the base system does not enable. So please let me take another shot at the changes before merging.

We are testing a version and should be close to resolving this. One problem is that it's not possible to **build** jemalloc 5.2.1 under FreeBSD without patching it

**Comment by leres** [comment]
Here's the version I wanted. It allows overriding jemalloc in the base system when you use --with-jemalloc

**Review by timwoj — APPROVED** [review]
Looks good to me. I'll merge this and cherry-pick it over to the release branch shortly.

**Comment by leres** [comment]
For completeness, here's a patch to what got merged to make it correctly detect --with-jemalloc=...
```
--- CMakeLists.txt      2022/01/12 01:30:47     1.1
+++ CMakeLists.txt      2022/01/12 01:33:52
@@ -296,7 +296,7 @@
 
 if (ENABLE_JEMALLOC)
     if (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
-        if (DEFINED ${JEMALLOC_ROOT_DIR})
+        if (DEFINED JEMALLOC_ROOT_DIR)
             # Look for jemalloc at a specific path
             find_package(JeMalloc)
         else()
```

**Pull request merged**
