### PR TITLE
Skip connection_state_remove for connection attempts

### PR DESCRIPTION
**Pull request by JustinAzoff**
Instead of raising both connection_attempt and connection_state_remove, only raise connection_attempt.

### CODE REVIEW

**Comment by JustinAzoff** [comment]
This drops the zeek -r runtime on a 1 million syn packet pcap on my laptop from 52s to 41s

**Comment by jsiwek** [comment]
Rather than break the semantics of `connection_state_remove`, would it work to introduce a new event that's raised conditionally, say `established_connection_remove`, then optimize our existing scripts to use that where possible ?

Otherwise breaking how `connection_state_remove` works sounds like a way to cause a bunch of non-obvious bugs in user scripts.  Our own test suite fails with the change as it is, so guessing it's common to assume the event is raised for every connection, especially since that's the documented behavior.

Might be helpful regardless to understand where the time is being spent -- is it just the number of extra function calls, are certain handler implementations not returning early enough and doing useless work, etc. ?  Because without a passing test suite, I can't tell at a glance if the performance improvement is legit -- it could come from not doing work that we actually still need to do.

**Comment by JustinAzoff** [comment]
ah, established_connection_remove is probably a better idea.

Almost all the connection_state_remove  events are things like

```
event connection_state_remove(c: connection) &priority=-5
	{
	if ( c?$mysql )
		{
		Log::write(mysql::LOG, c$mysql);
		delete c$mysql;
		}
	}
```

the krb  scripts  have an indirect function,  but are otherwise the same  eventually:

```scripts/base/protocols/krb/files.zeek
event connection_state_remove(c: connection)
	{
	fill_in_subjects(c);
	}

scripts/base/protocols/krb/main.zeek
event connection_state_remove(c: connection) &priority=-5
	{
	do_log(c);
	}
```

There  are 21 instances  of  this in base/protocols  which woulc be good candidates for using that new event.  I see a few things  in policy/ that my change would have broken, vlan-logging.zeek and  mac-logging.zeek use connection_state_remove to fill in some extra fields.

Another way to judge the perf impact for the 100% syns is to run something like this, to disable all the connection_state_remove events in the base/protocols directory:

```perl -pi -e  's/event connection_state_remove/event connection_state_removeXX/' $(grep 'event connection_state_remove' scripts/base/protocols  -rl|grep -v conn/)```

that stops 21 events from being raised.  Doing that has the same runtime improvement.  I think it's just that each event handler adds .5s or so to the runtime, and 21 of them add up.

**Comment by 0xxon** [comment]
To summarize the discussion - it seems as if we should introduce an "established_connection_remove" event and move most scripts over to that one - Jon likes that better, it seems like you agree - and I also think that is the better, less invasive change.

That means we should probably close this PR and open an issue for this. Unless anyone complains I will do that tomorrow.

**Comment by rsmmr** [comment]
Sounds good to me. Just for the record I'll add that `connection_state_remove` was originally indeed provided to have single guaranteed place for cleaning up any connection state. I'd be reluctant to give up that property and like the idea of a separate event much better.

**Comment by 0xxon** [comment]
Bug opened in #646.

**Pull request closed without merging**
