### PR TITLE
Fixing productive connections with missing SYN still considered partial after flipping direction.

### PR DESCRIPTION
**Pull request by rsmmr**
In #2191, we added endpoint flipping for cases where a connection starts with a SYN/ACK followed by ACK or data. The goal was to treat the connection as productive and go ahead and parse it. But the TCP analyzer could continue to consider it partial after flipping, meaning that app layers would bail out. #2426 shows such a case: HTTP gets correctly activated after flipping through content inspection, but it won't process anything because `IsPartial()` returns true. As the is-partial state reflects whether we saw the first packets each in direction, this patch now overrides that state for the originally missing SYN after flipping.

We actually had the same problem at another location already as well, where it only happened to work because of another state issue with flipping direction.  The 1st commit in this PR fixes that, but the corresponding unit test then broke after that change. This PR updates that logic as well to override the state.

This fix is a bit of a hack, but the best solution I could think of without introducing larger changes.

### CODE REVIEW

**Comment by awelzel** [comment]
Can't say I follow the state completely, but looking that `is_partial` flag and comments, but is the following hunk candidate for a `SetFirstPacketSeen()` invocation?

https://github.com/zeek/zeek/pull/2552/files#diff-c3d1ce1be2b00008ee17808c9bd6c630ee16e7201e2b6006d8cc5d40368bbad3R920-R921

```
		else if ( flags.ACK() && peer->state == analyzer::tcp::TCP_ENDPOINT_ESTABLISHED )
			{
			// No SYN packet from originator but SYN/ACK from
			// responder, and now a pure ACK. Problably means we
			// just missed that initial SYN. Let's not treat it
			// as partial and instead establish the connection.
			endpoint->SetState(analyzer::tcp::TCP_ENDPOINT_ESTABLISHED);
			is_partial = 0;
			}
```

**Comment by rsmmr** [comment]
Yeah, I think you're right, good catch. I've inserted that as well.

**Review by awelzel — APPROVED** [review]

**Comment by timwoj** [comment]
Can you throw a note in the NEWS about this before I merge it?

**Comment by rsmmr** [comment]
I'll update NEWS and merge.

**Pull request merged**
