### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by ckreibich**
CentOS Stream 8 is about to EOL so I'm including its removal here.

### CODE REVIEW

**Comment by timwoj** [comment]
The `asan_sanitizer` build failed here because of the coverage issues, which should be fixed by https://github.com/zeek/zeek/pull/3756 now.

**Comment by ckreibich** [comment]
I pushed a rebase just to iron that one out. I'll look at the Fedora 40 one shortly.

**Comment by timwoj** [comment]
Can we land the centos part of this and handle fedora 40 later?

**Comment by awelzel** [comment]
@bbannier / @ckreibich - I've pushed a follow-up to compile sqlite3.c with `-Wno-error`. Seems sensible to me in general given we just ship vanilla upstream.

**Comment by bbannier** [comment]
> @bbannier / @ckreibich - I've pushed a follow-up to compile sqlite3.c with `-Wno-error`. Seems sensible to me in general given we just ship vanilla upstream.

The `-Werror` addition seems fine to me though none of this would be an issue if we didn't build external deps with our own flags, e.g., with our custom vcpkg setup, I'd love to see that some day.

I cannot comment on the sqlite changes. The branch's commit message talks about bumping to 3.45.0, and the merge about 3.46.0. There are no instructions on how this patch was generated (e.g., what was the previous commit), so I cannot validate the bump.

**Comment by awelzel** [comment]
> The -Werror addition seems fine to me though none of this would be an issue if we didn't build external deps with our own flags, e.g., with our custom vcpkg setup, I'd love to see that some day.

Thanks. I'm going to move this forward then.

**Review by awelzel — APPROVED** [review]

**Comment by ckreibich** [comment]
Thanks @awelzel, I think that's the right call. I've left a post on the [SQLite forum](https://www.sqlite.org/forum/forumpost/f68e85b2c9) — perhaps they'll pick it up.

Fwiw, I did not imagine the `-O3` we talked about ... it's the default optimization level for build type "release" on my system (via `CMAKE_CXX_FLAGS_RELEASE`), and it's what triggers the warning:
```
$ gcc --version
gcc (GCC) 14.1.1 20240607 (Red Hat 14.1.1-5)

$ gcc -c -Wall -Werror -O2 sqlite3.c
$

$ gcc -c -Wall -Werror -O3 sqlite3.c
In function ‘sqlite3Strlen30’,
    inlined from ‘sqlite3ColumnSetColl’ at sqlite3.c:121296:10:
sqlite3.c:34653:28: error: ‘strlen’ reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
34653 |   return 0x3fffffff & (int)strlen(z);
      |                            ^~~~~~~~~
In function ‘sqlite3ColumnSetColl’:
cc1: note: source object is likely at address zero
cc1: all warnings being treated as errors
```

**Pull request merged**
