### PR TITLE
Remove use of Variable-Length-Arrays

### LINKED ISSUE #895: Warn/error on use of C++ variable-length-array
We might consider warnings/errors on use of VLAs in C++ code since it's not standard C++ and has more drawbacks than benefits.  E.g. maybe:

```diff
diff --git a/SetDefaultCompileFlags.cmake b/SetDefaultCompileFlags.cmake
index 1826cda..06c0c70 100644
--- a/SetDefaultCompileFlags.cmake
+++ b/SetDefaultCompileFlags.cmake
@@ -7,7 +7,7 @@ endif ()

 if ("${PROJECT_SOURCE_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
     set(EXTRA_COMPILE_FLAGS	 "-Wall -Wno-unused")
-    set(EXTRA_COMPILE_FLAGS_CXX "-Wno-register")
+    set(EXTRA_COMPILE_FLAGS_CXX "-Wno-register -Werror=vla")

     if ( NOT CMAKE_BUILD_TYPE )
	 if ( ENABLE_DEBUG )
```

### PR DESCRIPTION
**Pull request by jsiwek**
Fixes #895

Same branch in other repos need merging with this:
* https://github.com/zeek/bifcl/pull/5
* https://github.com/zeek/binpac/pull/11
* https://github.com/zeek/cmake/pull/20

### CODE REVIEW

**Comment by timwoj** [comment]
Just at a quick glance, is there any reason to use `std::unique_ptr<type[]>` and the `.get()` method over `std::array<type>` and the `.data()` method?

**Comment by ZekeMedley** [comment]
`std::array`'s size is a fixed at compile time so anytime you need to allocate some memory at runtime its a no-go. I'd imagine that's the case for using `std::unique_ptr` for most of the cases here.

**Comment by timwoj** [comment]
I could have sworn there was a way to do a variable-length std::array. Maybe I'm thinking of something that was proposed and didn't make it in. But yah you're right, it's a template param so no doing variable-length. It just feels ugly to use a `unique_ptr` for an array like that, but it's probably the safest way.

**Comment by 0xxon** [comment]
Next similar question - could we use std::vector instead of the std::unique_ptrs?

That would look a bit nicer - and they are dynamically sized.

**Comment by jsiwek** [comment]
Generally, what we choose as replacement is all implementation detail and not anything visible in public APIs, so not too picky on what's decided, but these are basic requirements/wishlist:

* use heap allocation, not stack allocation
* automatic/stack-based lifetime (RAII) since it's just easier in terms of memory management

`std::unique_ptr<type[]>` is a fairly direct translation of VLA that hits those points.

> EDIT: ah yah, it was std::dynarray, which was proposed for C++14 and didn't make the cut.

Cool, hadn't heard of that, but only briefly reading around, see some claim that implementations are at liberty to allocate on stack, which they would probably be smart to do within reason, but still sketchy and what we wanted to avoid.

> Next similar question - could we use std::vector instead of the std::unique_ptrs?
> 
> That would look a bit nicer - and they are dynamically sized.

Don't recall any of the replacement sites actually need to take advantage of dynamic sizing -- they're fine with a fixed-size buffer to pass along to some lower level consumer API like `snprintf`, `memcmp`, `memcpy` that don't care if we used a fancy C++ container to allocate the buffer anyway.  So disagree it looks nicer since the additional complexity of how a `vector` reserves capacity is beyond what we care about for these usages.

**Pull request merged**
