### PR TITLE
Add external dependency include paths to `zeek-config --include_dir`

### PR DESCRIPTION
**Pull request by jsiwek**
Fixes https://github.com/zeek/zeek/issues/1180

Related PR: https://github.com/zeek/cmake/pull/24

This helps ensure successful compilation of a plugin that includes a
Zeek header which includes an external dependency header even if the
plugin itself doesn't necessarily depend on that external library.

### CODE REVIEW

**Review by rsmmr — APPROVED** [review]
I keep wondering if there's a different way of doing this that doesn't require manually listing them all, but can't think of much, so fine with me.

Just to double check: the decencies are really need by the headers we install? (vs. being included only my implementation files).

**Comment by jsiwek** [comment]
> Just to double check: the decencies are really need by the headers we install? (vs. being included only my implementation files).

These are included from a Zeek header: pcap, zlib, openssl, kerberos, gperftools
These are not included from a Zeek header: resolv.h, jemalloc, fts, mmdb

Given the ones that did find their way into a Zeek header, I find more comfort in preemptively adding the others to the include list or else plugin builds may suddenly find themselves breaking if they do sneak in.  Alternatively, we could try to resolve via new development/review policies, but I'm not confident that would work well.  Other alternative is to add automated test cases for building 100+ plugins, one to try including each Zeek header, but guessing that may be excessive/inefficient.

I don't have general issues with trying to go down a route of "let's (re)structure things to avoid depending on external dependency headers from Zeek headers", just that requires a more involved solution and prolonged/consistent vigilance.

Any further thought, or this PR still seem fine?

**Comment by rsmmr** [comment]
I'd leave the those out which aren't included by headers. It just seems unnecessary to let them leak to the outside if it's an implementation detail. If they move from detail to interface, that's something that reviewing should catch and yes, ideally, CI as well. Would it help to create just one test that includes all headers? Similar to the load-all-scripts test for Zeek scripts?

**Comment by jsiwek** [comment]
> I'd leave the those out which aren't included by headers. It just seems unnecessary to let them leak to the outside if it's an implementation detail.

Put like that, I agree and will remove them.

> Would it help to create just one test that includes all headers? Similar to the load-all-scripts test for Zeek scripts?

Yeah, could be, but not going to look into it now.  There's these other aspects of maintainability-burden to it, too:
* Needs explicit CI setup to install all external dependencies to non-standard locations (even those dependencies not currently referenced from Zeek headers).
* Any new dependency will need that same CI treatment on arrival.
* The test has to be maintained for every additional/removal of a header file.

**Pull request merged**
