### PR TITLE
Migrate to the new ALM-enabled Broker version

### PR DESCRIPTION
**Pull request by Neverlord**
Zeek-side adjustments for the ALM (Application Layer Multicast) Broker version.

Not yet ready to merge! Filing for CI.

### CODE REVIEW

**Comment by timwoj** [comment]
@rsmmr asked me to run a benchmark pass on this since the changes have stabilized. Here's the easy pass, the longer pass should be done tomorrow. `master` is first, branch is second:

```
Running bench for /mnt/data/test_data/ixia_http+dns_5min_500Mbps.pcap
Average memory: 2966320 KB
Average CPU: 68.83%

Running bench for /mnt/data/test_data/ixia_http+dns_5min_600Mbps.pcap
Average memory: 3426949 KB
Average CPU: 76.43%

Running bench for /mnt/data/test_data/ixia_RamEntDataCenter2_5min_500Mbps.pcap
Average memory: 2530277 KB
Average CPU: 70.50%

Running bench for /mnt/data/test_data/ixia_RamEntDataCenter2_5min_500Mbps.pcap
Average time spent: 268.06 seconds
Average memory usage: 2395125 KB



Running bench for /mnt/data/test_data/ixia_http+dns_5min_500Mbps.pcap
Average memory: 2970250 KB
Average CPU: 68.47%

Running bench for /mnt/data/test_data/ixia_http+dns_5min_600Mbps.pcap
Average memory: 3425630 KB
Average CPU: 76.63%

Running bench for /mnt/data/test_data/ixia_RamEntDataCenter2_5min_500Mbps.pcap
Average memory: 2541102 KB
Average CPU: 69.57%

Running bench for /mnt/data/test_data/ixia_RamEntDataCenter2_5min_500Mbps.pcap
Average time spent: 272.85 seconds
Average memory usage: 2396368 KB
```

**Comment by rsmmr** [comment]
@timwoj I assume output looks similar as well?

**Comment by timwoj** [comment]
I generally don't keep the output from this benchmark, but I can modify the scripts and rerun it. It shouldn't be too much effort.

**Comment by 0xxon** [comment]
I just deployed this on my (admittedly tiny) home Zeek installatio - and things look ok.

There is one rather huge compiler warning that you might know about already:

```
[568/1369] Building CXX object auxil/br.../broker.dir/src/internal/connector.cc.o
In file included from ../auxil/broker/caf-incubator/libcaf_net/caf/net/length_prefix_framing.hpp:17,
                 from ../auxil/broker/src/internal/connector.cc:19:
../auxil/broker/caf-incubator/libcaf_net/caf/net/message_flow_bridge.hpp: In instantiation of ‘caf::net::message_flow_bridge<T, Trait, Tag>::message_flow_bridge(caf::net::message_flow_bridge<T, Trait, Tag>::consumer_resource_t, caf::net::message_flow_bridge<T, Trait, Tag>::producer_resource_t, Trait) [with T = broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >; Trait = broker::internal::wire_format; Tag = caf::tag::message_oriented; caf::net::message_flow_bridge<T, Trait, Tag>::consumer_resource_t = caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >; caf::net::message_flow_bridge<T, Trait, Tag>::producer_resource_t = caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >]’:
../auxil/broker/caf-incubator/libcaf_net/caf/net/length_prefix_framing.hpp:51:43:   required from ‘caf::net::length_prefix_framing<UpperLayer>::length_prefix_framing(Ts&& ...) [with Ts = {caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, broker::internal::wire_format}; UpperLayer = caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented>]’
../auxil/broker/caf-incubator/libcaf_net/caf/net/stream_transport.hpp:100:71:   required from ‘caf::net::stream_transport_base<Policy, UpperLayer>::stream_transport_base(Policy, Ts&& ...) [with Ts = {caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, broker::internal::wire_format}; Policy = caf::net::default_stream_transport_policy; UpperLayer = caf::net::length_prefix_framing<caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented> >]’
../auxil/broker/caf-incubator/libcaf_net/caf/net/stream_transport.hpp:506:71:   required from ‘caf::net::stream_transport<UpperLayer>::stream_transport(Ts&& ...) [with Ts = {caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, broker::internal::wire_format}; UpperLayer = caf::net::length_prefix_framing<caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented> >]’
../auxil/broker/caf-incubator/libcaf_net/caf/net/socket_manager.hpp:266:69:   required from ‘caf::net::socket_manager_impl<Protocol>::socket_manager_impl(caf::net::socket_manager_impl<Protocol>::socket_type, caf::net::multiplexer*, Ts&& ...) [with Ts = {caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, broker::internal::wire_format}; Protocol = caf::net::stream_transport<caf::net::length_prefix_framing<caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented> > >; caf::net::socket_manager_impl<Protocol>::socket_type = caf::net::stream_socket]’
../auxil/broker/caf/libcaf_core/caf/make_counted.hpp:19:27:   required from ‘caf::intrusive_ptr<T> caf::make_counted(Ts&& ...) [with T = caf::net::socket_manager_impl<caf::net::stream_transport<caf::net::length_prefix_framing<caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented> > > >; Ts = {caf::net::stream_socket, caf::net::multiplexer*&, caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, broker::internal::wire_format}]’
../auxil/broker/caf-incubator/libcaf_net/caf/net/socket_manager.hpp:388:28:   required from ‘auto caf::net::make_socket_manager(caf::net::socket_type_t<App, Layers ...>, caf::net::multiplexer*, Ts&& ...) [with App = caf::net::stream_transport<caf::net::length_prefix_framing<caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented> > >; Layers = {}; Ts = {caf::async::consumer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, caf::async::producer_resource<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > > >, broker::internal::wire_format}; caf::net::socket_type_t<App, Layers ...> = caf::net::stream_socket]’
../auxil/broker/caf-incubator/libcaf_net/caf/net/length_prefix_framing.hpp:267:40:   required from ‘caf::error caf::net::run_with_length_prefix_framing(caf::net::multiplexer&, Socket, const settings&, caf::async::consumer_resource<T>, caf::async::producer_resource<T>, Trait, TransportArgs&& ...) [with Transport = caf::net::stream_transport; Socket = caf::net::stream_socket; T = broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >; Trait = broker::internal::wire_format; TransportArgs = {}; caf::settings = caf::dictionary<caf::config_value>]’
../auxil/broker/src/internal/connector.cc:230:79:   required from here
../auxil/broker/caf-incubator/libcaf_net/caf/net/message_flow_bridge.hpp:254:23: warning: ‘caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented>::in_res_’ will be initialized after [-Wreorder]
  254 |   consumer_resource_t in_res_;
      |                       ^~~~~~~
../auxil/broker/caf-incubator/libcaf_net/caf/net/message_flow_bridge.hpp:251:9: warning:   ‘broker::internal::wire_format caf::net::message_flow_bridge<broker::cow_tuple<broker::endpoint_id, broker::endpoint_id, broker::cow_tuple<broker::packed_message_type, short unsigned int, broker::topic, std::vector<std::byte, std::allocator<std::byte> > > >, broker::internal::wire_format, caf::tag::message_oriented>::trait_’ [-Wreorder]
  251 |   Trait trait_;
      |         ^~~~~~
../auxil/broker/caf-incubator/libcaf_net/caf/net/message_flow_bridge.hpp:44:3: warning:   when initialized here [-Wreorder]
   44 |   message_flow_bridge(consumer_resource_t in_res, producer_resource_t out_res,
      |   ^~~~~~~~~~~~~~~~~~~

```

(GCC 9.4.0 on Ubuntu 20.04)

**Comment by Neverlord** [comment]
@0xxon thanks for the hint. Should be fixed upstream.

**Comment by Neverlord** [comment]
Troubleshooting that OpenSSL issue was quite tedious. I've basically put back in the OpenSSL initialization that @0xxon had just removed and also added threading-related initialization that Broker used to do. Didn't see any `SSL_CTX_new` failure this time. My guess is that the lazy-initialization that OpenSSL does when not initializing it manually is broken in multi-threaded environments.

**Pull request merged**
