### PR TITLE
RFC: Reformat code using Allman bracing style instead of Whitesmiths [skip ci]

### PR DESCRIPTION
**Pull request by timwoj**
This is an RFC version for switching our formatting to Allman mode. It's effectively just moving the braces one column to the left, but there may be other changes as well.

### CODE REVIEW

**Comment by vpax** [comment]
It would be handy to see a version of these diffs that suppresses changes that are only due to whitespace, which right now overwhelmingly dominate looking at the changes. (Same for @bbannier 's example run.)

**Comment by timwoj** [comment]
It's possible to do that from the Github interface by adding `?w=1` to the URL.

**Comment by vpax** [comment]
> It's possible to do that from the Github interface by adding `?w=1` to the URL.

Aha! Great to know, thanks. The changes then look non-scary :-).

**Comment by timwoj** [comment]
Closing this in favor of https://github.com/zeek/zeek/pull/3360

**Pull request closed without merging**
