### PR TITLE
fuzzers: Add LDAP fuzzing

### PR DESCRIPTION
**Pull request by awelzel**
LDAP supports both, UDP and TCP as separate analyzers. The corpus
is identical, however. Started to hit the TLS analyzer fairly
quickly, too.

Closes https://github.com/zeek/zeek/issues/3860

---

* One fix in the scripts to avoid that was tickled fairly quickly through the TCP fuzzer:

    expression error in <...>/protocols/ldap/main.zeek, line 270: field value missing (LDAP::m$opcode)

* This PR also removes `--disable-spicy` from the sanitizer builds. It appears that a) Spicy changes and b) using newer GCC for asan_sanitizer

### CODE REVIEW

**Comment by awelzel** [comment]
We've also enabled Spicy on oss-fuzz: https://github.com/google/oss-fuzz/pull/12298

**Comment by awelzel** [comment]
Hmm... I'm running into snags enabling spicy for the sanitizer builds (which are smoke testing the fuzzers and the corpus - so it makes sense for LDAP).

* UBSAN isn't able to build the analyzers (https://github.com/zeek/spicy/issues/1817 duplicate of https://github.com/zeek/zeek/issues/3670 ?).

* TSAN isn't happy with one of the tests (`replaces-conflicts`) which seems due to `Fatal()`  triggered while loading `.hlto` when initializing globals? (that's hand-wavy-guessing).
  ```
  fatal error: redefinition of protocol analyzer spicy::SSH_1
  +ThreadSanitizer: main thread finished with ignores enabled
  +  One of the following ignores was not ended (in order of probability)
  +  Ignore was enabled at:
  +    #0 __cxx_global_var_init /zeek/testing/btest/.tmp/spicy.replaces-conflicts/../SSH_ea2172540d160548-1cb0a74c78dea7b6.cc (ssh.hlto+0x5632) (BuildId: 66c471d5c2eb9455190eeadbfdd1debce5a5171c)
  +    #1 __cxx_global_var_init /zeek/testing/btest/.tmp/spicy.replaces-conflicts/../SSH_ea2172540d160548-1cb0a74c78dea7b6.cc (ssh.hlto+0x5632) (BuildId: 66c471d5c2eb9455190eeadbfdd1debce5a5171c)
  +    #2 <null> <null> (ld-linux-x86-64.so.2+0x571e) (BuildId: 3e81740f816ee1521a87e439c16ebfde46f147a5)
  +    #3 hilti::rt::Library::open() const /zeek/build/auxil/spicy/hilti/runtime/../../../../../auxil/spicy/hilti/runtime/src/library.cc:59:24 
  ```

  https://cirrus-ci.com/task/5825487946121216?logs=test#L2038-L2039

* ASAN isn't happy due to `--coverage` usage, I'm seeing this locally, too.
  https://cirrus-ci.com/task/6529175387897856?logs=test#L1839-L1842
  ```
  "/zeek/testing/btest/.tmp/spicy.analyzer-tag/ssh.hlto": /zeek/testing/btest/.tmp/spicy.analyzer-tag/ssh.hlto: undefined 
  symbol: __gcov_merge_add
  ```
  That one seems to be a missing `--coverage` in the LDFLAGS.

**Comment by awelzel** [comment]
@timwoj / @bbannier - this should now work and we'll have Spicy enabled also in sanitizer builds as well as LDAP ASAN parsing.

**Review by timwoj — APPROVED** [review]
:shipit:

**Pull request merged**
