### PR TITLE
Integrate CAF 0.18 into the new ALM backend

### PR DESCRIPTION
**Pull request by Neverlord**
This is a followup to #1156 and gets rebased before leaving *draft* status. Also depends on https://github.com/zeek/broker/pull/149.

### CODE REVIEW

**Comment by rsmmr** [comment]
We said to upgrade to 0.18 either way (even if ALm doesn't make it), so I set this to 4.0.0.

**Comment by rsmmr** [comment]
Moving to 4.1.0 along with #1156

**Comment by jsiwek** [comment]
@Neverlord since CAF 0.18 is merged already from #1319, can this get closed as obsoleted or plan to consolidate with #1156 ?   The later has some pending plans/feedback that are probably more important to remember/track, so seems best to use that one going forward.

**Comment by Neverlord** [comment]
Yep, this one became obsolete.

**Pull request closed without merging**
