### PR TITLE
Integrate paraglob with Zeek

### LINKED ISSUE #268: Add support for tables indexed by globs
The challenge is to find an efficient data structure that supports parallel glob matching for large numbers of patterns. We have an earlier attempt at this ([paraglob](https://github.com/zeek/paraglob)) that didn't show the anticipated performance; should revisit/reconsider how to do this.

### PR DESCRIPTION
**Pull request by ZekeMedley**
Resolves #268.

This is a continuation of https://github.com/zeek/zeek/pull/371, sorry about the duplication. GitHub has lost track of what repository that pull request is coming from.

This follows up on what [Johanna suggested](https://github.com/zeek/zeek/pull/371#issuecomment-494457163) about making paraglob serializable and uses smart pointers in `ParaglobVal` to keep memory safe.

GitHub seems to think that I added some code to `src/broker/Manager.cc` and `src/input/readers/ascii/[Ascii.cc/Config.cc]`. Both files are the same as the master branch though, so I'm not sure what is going on there. If anyone has any suggestions on how to fix that I'd really appreciate it.

### CODE REVIEW

**Comment by jsiwek** [comment]
Please close #371 if it's no longer needed.

I didn't look closely at anything here except noticed the failing Travis builds, can you take a look at getting that fixed?  Seems one platform was complaining because `-std=c++11` may not be getting used for building paraglob and then also the `language.paraglob` test is still using `bro`, but should now use `zeek`.

**Comment by ZekeMedley** [comment]
@0xxon if you get a chance to look over the serialization code in this I'd really appreciate it. It seems to work well, but I don't quite have a deep understanding of how serialization is working under the hood and would love a sanity check. Particularly in `src/SerialTypes.h` I was following along with other opaque types, but its possible there is some extra code in there.

**Comment by 0xxon** [comment]
One more comment - while I will merge this as it is at the moment, it would be really great to have more documentation about this in Zeek too - along the lines of your blog post.

I also think the supported patterns are currently not explained everywhere (not even in the paraglob repo itself).

Would you mind adding that to zeek-docs and making another pull request there? :)

**Comment by ZekeMedley** [comment]
Great. Thanks so much for putting together the merge & doing all those fixes pre-merge. 

I made a pull request to the docs [here](https://github.com/zeek/zeek-docs/pull/5) and a pull request to the paraglob repo [here](https://github.com/zeek/paraglob/pull/10) which update them to clarify that the patterns are strings, not the builting `pattern` type and change `paraglob_get` to `paraglob_match`. 

If you have any suggestions about how paraglob should be added to `zeek-docs` that are different from the way I've added it, I'm open to move the documentation around. Right now I added a blurb about it to `opaque type`.

**Pull request merged**
