### PR TITLE
add some dhcp options

### PR DESCRIPTION
**Pull request by jrwren**

### CODE REVIEW

**Comment by jsiwek** [comment]
Thanks for the PR, would you be able to add unit tests with sample pcaps?

**Comment by jrwren** [comment]
I would love to eventually add some tests with sample pcaps, assuming you can point me to some existing ones for example reference.

**Comment by jsiwek** [comment]
Great, yes I can give references.

The unit test suite is in the `testing/btest/` subdir.  There's a README there (and also at https://github.com/zeek/btest itself) that may also help.

You'd put small-ish sample pcaps in `testing/btest/Traces/dhcp/` and then write a unit test file under `testing/btest/scripts/base/protocols/dhcp/`.

You can see the other DHCP tests there, but probably I'd test the particular changes in this PR a bit differently, more like this SSL test, but using a `dhcp_message` event handler instead: https://github.com/zeek/zeek/blob/a342090f18f9d9bb3ccb0e7dd6a1e73944a63934/testing/btest/scripts/base/protocols/ssl/handshake-events.test

Then you'd check the output of the test using `btest -d <test_file_path>` is as you expect, then confirm and add a baseline with `btest -U <test_file_path>`, then commit changes + new files and push.

**Comment by jsiwek** [comment]
Hi, just wondering if you had any trouble with adding tests that I could help with?  Or if you have limited time, but could still contribute sample pcaps that would exercise the new code, feel free to just send me those and I can take care of creating unit tests.

**Comment by jrwren** [comment]
It's on my TODO, but I've not allocated time to it. I'll have to generate the pcaps too. Sorry, it may be a while.

**Comment by 0xxon** [comment]
Hi,

I just wanted to check if you still plan working on this :).

Thanks a lot,
 Johanna

**Comment by jrwren** [comment]
I am, and in fact, I recently found I can set aside some time to do so. Expect something within a couple of weeks.

**Comment by jrwren** [comment]
I added a btest with trace and stdout, thank you for the guidance. I hope this is satisfactory.

**Comment by jsiwek** [comment]
Thanks for adding a test case, I merged this with minor changes:

- Renamed some of the fields for consistency since there was already a "dns_servers" field:
  - timeserver_list -> time_servers
  - nameserver_list -> name_servers
  - ntpserver_list -> ntp_servers

- The time offset option was being parsed as a `uint32`, but spec says it's a two-complement 32-bit integer, so changed it to `int32`.  The time offset in the test case's pcap is now interpreted as -18000, which also aligns with Wireshark's interpretation.

**Pull request merged**
