### PR TITLE
Rebase patricia code on upstream version

### LINKED ISSUE #1656: Rebase patricia.{c,h} on upstream
This is a follow-on to #1644. Our versions of the patricia files seem a bit out of date from what looks like the upstream version at https://github.com/CAIDA/cc-common/tree/master/libpatricia. We should consider rebasing them to pick up any additional fixes that we don't have.

Note that we have a few custom changes to these files for Zeek, which should be preserved. These are the `patricia_search_all` function and the `data_fn_t` and `prefix_data_fn_t` function pointer types.

### PR DESCRIPTION
**Pull request by timwoj**
Fixes #1656 

I figured out what was causing our test to fail. I left that little bit commented out with a TODO note until someone can actually figure out why it fails. Otherwise I got all of the other upstream changes merged. We should consider importing these changes into the zeek/pysubnettree repo, since that repo keeps a copy of these files as well.

### CODE REVIEW

**Comment by timwoj** [comment]
Upstream also approved the PR that I sent them to reformat all of their code in a sane manner, based on an existing clang-format configuration in one of their other projects. I'll reformat ours once that's landed in their master.

**Review by rsmmr — COMMENTED** [review]
This looks all good, but we should probably figure out that TODO before applying.

**Comment by timwoj** [comment]
The TODO failure is because of a bug introduced in 552a24e07c55a3db0688a4e1a2d002a708b74b2e. `PrefixTable::Lookup` has two versions, one which takes a `ValPtr` and a `bool`, and one which takes an `IPAddr`, an integer `width`, and a `bool`. This calls the wrong one, because the bool argument on the latter function has a default value. It calls it with a `width` of `1` which fails the check in the patricia code.

I'm confused as to what the intention was though because if I fix it and pass a large enough width value (128), it gives me the output that fails the test. But if i fix it to both pass 128 and false for the boolean argument, it returns what the test was expecting. @sethhall Do you know what the intention was here? The Lookup methods in PrefixTable havent changed in about a decade other than for the namespacing work.

**Comment by timwoj** [comment]
See the above commit for a "fixed" version. I'm not a big fan of it because it hard-codes that width value to something semi-valid. Unfortunately, if I add a lookup for the proper width by checking for the address family (similar to how `addr_to_subnet` in zeek.bif does it), it sets it to 32 even though patricia thinks it's an IPv6 address.

**Review by rsmmr — APPROVED** [review]
Interesting. This looks like the right fix to me.

I don't think it called the wrong `Lookup` (they differ on the type of the 1st argument), but it did mess up the arguments. Hardcoding the width seems right: The other `Lookup()` that takes a `Val` internally also just sets width to 128.

**Pull request merged**
