### PR TITLE
remove deprecated union and timer types, addressing #1898

### PR DESCRIPTION
**Pull request by matthewluckie**

### CODE REVIEW

**Review by timwoj — CHANGES_REQUESTED** [review]
What you've done so far looks good to me. As @vpax mentioned in the issue, you can also remove the script-level bits for `list`, which means removing `TOK_LIST` from scan.l and the handling of it from parse.y. The actual internal notion of a list needs to stay (so anything handling `TYPE_LIST`) but the script parser bits can all go.

**Comment by matthewluckie** [comment]
OK, I think I've done that now.

**Comment by 0xxon** [comment]
Actually, Vern pointed out that we might want to keep the script-level token of list - basically to reserve the keyword. I think I agree with him - and would prefer keeping that.

@rsmmr, @vpax - do you have opinions one way or the other?

**Comment by rsmmr** [comment]
> Actually, Vern pointed out that we might want to keep the script-level token of list - basically to reserve the keyword. I think I agree with him - and would prefer keeping that.

Agree on reserving the keyword, but I'd otherwise remove all code around it that's not in active use (i.e., just leave it wired into lexer/parser and ensure there's some kind of error message if people happen to use it).

**Comment by matthewluckie** [comment]
sigh, i messed up.  i will open a new PR, but this time not committing changes to master.  sorry for the noise.

**Pull request closed without merging**
