### PR TITLE
Reformat all of the source using clang-format

### PR DESCRIPTION
**Pull request by timwoj**
Clang-format 12.0.1 is out, which includes all of the changes needed to reformat the Zeek code close to what currently exists. That's not to say there isn't a ton of changes still, but clang-format mostly-properly supports the crazy Whitesmiths "standard" now.

### CODE REVIEW

**Comment by rsmmr** [comment]
`Files changed: 690` might be a new record! :-)

**Comment by rsmmr** [comment]
I did some more spot checking.  Apart from lots of little stuff,  the two main types of changes I see are formatting for switch-statements and replacing a bunch of TABs with spaces between header and body of inline methods.

Personally, I'm fine with this and would argue for going ahead with the change after giving notice to the community. 

For people with maintaining branches, the best way to port them over is probably to run clang-format on their code *before* rebasing.

**Comment by 0xxon** [comment]
I also noticed the switch change - I actually like the new one better - it seems more consistent.

I second the opinion that this is a good change, and we should go ahead.

**Comment by timwoj** [comment]
I rebased the branch now that Vern's massive ZAM work is merged. I'm also moving this out of draft status.

**Comment by timwoj** [comment]
> Files changed: 690 might be a new record! :-)

Make that 720 😄

**Pull request merged**
