### PR TITLE
Organized and added to the shipped file identification signatures.

### PR DESCRIPTION
**Pull request by sethhall**
Unfortunately, continuing in the vein of the file type identification code, there are no tests.  I would just appreciate if someone could take a look through the changes to see if I did anything obviously wrong.

 - Added ISO 9660 disk image
 - Created new files for categorizing signatures better.
   - executable.sig - Executable (and bytecode) files.
   - java.sig - Java related files (class/jar, etc).
   - programming.sig - Mostly scripting language identification

### CODE REVIEW

**Comment by jsiwek** [comment]
* CI/tests fails
* technically, removing a signature, moving a signature to a difference file, or renaming a signature file are all breaking changes.  Guessing most people won't care much, but seems at least worth a NEWS entry to mention it (unless there's other ideas/opinions on how to accommodate)

**Comment by sethhall** [comment]
Thanks Jon.  When I get a chance I'll work on this some more and get it ready.  Thanks for taking a peek.

**Comment by 0xxon** [comment]
@sethhall - just wanted to check if you still are planning to do this in the forseeable future.

**Comment by sethhall** [comment]
Yep! Hoping to get this all fixed early this week.

**Pull request merged**
