### PR TITLE
Install btest tooling with the distribution

### LINKED ISSUE #1431: Install Zeek btest canonizers
Right now it's annoying to need to include all of the little btest canonifier scripts with an external Zeek script package if you want to use those that are shipped with Zeek.

Seems like we could just install those scripts somewhere with a Zeek install and then have a convention for referencing them in a btest.cfg file.

### PR DESCRIPTION
**Pull request by ckreibich**
This adds $PREFIX/share/btest to the installation and puts Zeek's btest canonifiers, random.seed, and pcaps in there. For example, in order to use the `diff-canonifier` you'd say `$(zeek-config --btest_tools_dir)/scripts/diff-canonifier` from your package's btest.

Pcaps can be skipped via `configure --disable-btest-pcaps`. I don't feel strongly here and could also see opt-in — just let me know, or feel free to change upon merge.

Also adds help output to `zeek-config`, since it has a lot of options these days.

Resolves #1431.

### CODE REVIEW

**Comment by ckreibich** [comment]
@0xxon I was wondering whether to skip any steps here in binary packaging mode ... I believe the answer is no? Let me know if got that wrong.

For binary packages, the stuff in $PREFIX/share/btest should be added in the development packages. I'm catching up on `osc`, maybe I can put a patch together for you. :crossed_fingers:

**Comment by rsmmr** [comment]
Haven't fully reviewed, but I like this generally!

**Comment by 0xxon** [comment]
> @0xxon I was wondering whether to skip any steps here in binary packaging mode ... I believe the answer is no? Let me know if got that wrong.

The answer is no.
> For binary packages, the stuff in $PREFIX/share/btest should be added in the development packages. I'm catching up on `osc`, maybe I can put a patch together for you. 🤞

If you feel like it - sure. Otherwise I will obviously do this.

**Review by 0xxon — APPROVED** [review]

**Comment by 0xxon** [comment]
Looking at this again - to me this all looks good.

Unless anyone has any problems with this, I am just going to merge it in the next few days.

**Comment by ckreibich** [comment]
Thanks for picking this up, Johanna. I let this sit there for a bit given the discussion over in #1431 ... I still land on either templating or this PR, so I'm on board. We may want to add a note in `testing/README` (or the subdirectories) to stress that changes should strive to be backward-compatible. (Happy to do that, just let me know.)

**Comment by 0xxon** [comment]
If you feel like doing that - sure. And - just to give this a bit more time - I will wait till Monday next week, and if no one has any complaints by then I am going to merge it.

**Pull request merged**
