### PR TITLE
Implement ERSPAN type II and ERSPAN type III support

### PR DESCRIPTION
**Pull request by stu-h**
Same caveat as @sethhall in commit https://github.com/zeek/zeek/commit/59f0477d29b168673b0e706fd3f458bef0116f04

Tested working, but I haven't included test traces. I can provide some if required but they are just samples I found on the Internet.

### CODE REVIEW

**Comment by jsiwek** [comment]
Thanks, ideally we do want PRs to include unit tests, so if you can create those to test the new ERSPAN II and III code paths, that would be best (please use small/minimal pcap files).  Or else providing links to pcaps we can use to create the tests ourselves is appreciated.

**Comment by stu-h** [comment]
Okay, I'll put together a few traces extracting packets from the samples I found. 

Will replicating the tests that Seth put in for the first ERSPAN implementation be sufficient?

**Comment by jsiwek** [comment]
Thanks, yes Seth's test looks like a good reference to imitate (essentially just looking for tests that run the pcaps through Bro and then use some log file or output produced by that as proof that things work right).

**Comment by jsiwek** [comment]
I went ahead and merged this with some changes: additional truncation checks and handling for the optional sub-header of ERSPAN type III.  Also added a unit test for type II, but would be great if you still had a chance to either add a test for type III or provide a sample pcap I can use to create one.

**Pull request merged**
