### PR TITLE
Adapt to upstream API adjustments

### PR DESCRIPTION
**Pull request by Neverlord**
Zeek-side adjustments for https://github.com/zeek/broker/pull/376.

### CODE REVIEW

**Comment by Neverlord** [comment]
The error on `arm_debian11` seems unrelated, at least it's also read on the main branch with the OOM error.

**Review by timwoj — APPROVED** [review]
Other than my comments on the associated broker PR, these changes on the zeek side look fine.

**Comment by Neverlord** [comment]
The last push only updated the Broker submodule to the latest commit.

**Comment by timwoj** [comment]
I brought in the lastest broker master after merging the upstream PR, and rebased this on the latest Zeek master. I'll merge it once it passes CI.

**Pull request merged**
