### PR TITLE
updated to mention notice_alarm.log by name, which took the place of alarm.log

### PR DESCRIPTION
**Pull request by duffy-ocraven**
clarifying, where the file was formerly named alarm.log

### CODE REVIEW

**Comment by timwoj** [comment]
I think you caught some extra stuff in this commit. Can you rebase it on top of master to get rid of the extra changes?

**Comment by duffy-ocraven** [comment]
After that git add doc git commit git push it now says "Able to merge". Does that get it where you want?

**Comment by timwoj** [comment]
For some reason a bunch of submodule pointers are getting updated by your changes. I can just fix them in the merge though.

**Comment by timwoj** [comment]
I cherry-picked the changes to alarm.log and skipped the changes to the submodules. The docs action will pick up and fix the doc submodule when it runs later.

**Pull request closed without merging**
