### PR TITLE
Update libkqueue submodule to v2.5.0

### PR DESCRIPTION
**Pull request by timwoj**
This doesn't fix all of the ThreadSanitizer issues I reported in libkqueue, but it's been a while since we updated this and they've pushed a couple of new versions since then.

This PR is mostly just for CI coverage.

### CODE REVIEW

**Comment by 0xxon** [comment]
Seems like that might causes interesting test failures :)

**Comment by timwoj** [comment]
Yah, @ckreibich and I spent a little time staring at it yesterday. It appears that libkqueue added some code between 2.4 and 2.5 that eats the `SIGCHLD` signal, but only on Linux kernels <= 5.3. We were depending on that signal to handle detecting when a supervisor stem dies, and it's interfering with our ability to do so. I think there's a way you can use `kqueue()` to watch for that status though, so I'm going to tinker with switching supervisor over to use that instead.

**Comment by timwoj** [comment]
I ended up adding another commit to our libkqueue fork to disable their `evfilt_proc` code. We're not using that filter and it was added in v2.5, so disabling it doesn't appear to break anything on our side. I left a big note in the commit about what is going on there.

**Comment by timwoj** [comment]
This passed CI. I'm waiting to run a benchmark pass on os-perf with it just to validate no differences between this and `master`. I'll take care of that in the next couple of days.

**Comment by timwoj** [comment]
Benchmarks look good. Within any sort of margin of error (1% or so, both faster and slower on various tests). This should be fine to merge.

**Pull request merged**
