### PR TITLE
add new "successful_connection_remove" event

### LINKED ISSUE #646: Introduce established_connection_remove event
Measurements of @JustinAzoff show that the current use of ```connection_state_remove``` introduced quite a bit of performance overhead. For more details, see #642 

```connection_state_remove``` is raised for all connection state removal - including of connections that were never established. However, in most cases where the event is used, the code in it only is meaningful if a connection was established. It is still called in these cases - which seems to lead to a fair amount of performance overhead.

The solution to this problem which was discussed in #642 is to introduce a new event, called ```established_connection_remove```. This event will have the same semantics as ```connection_state_remove``` - but will only be called for connections that got established. Simultaneously we can move nearly all uses of ```connection_state_remove``` over to the new event - which should improve performance quite a bit.

### PR DESCRIPTION
**Pull request by jsiwek**
Fixes #646

- I used "credible" instead of original thought of "established" in the event name since the later has pre-existing meaning only in context of TCP conns, but this new event would be used for UDP as well.  It's the least worst name I could think of.  Other ideas welcome.  EDIT: amended/force-pushed the name back to original idea of "established_connection_remove" and then later to "successful_connection_remove".

- These changes might not actually result in 100% compatibility with external scripts like I thought because using a new event still ends up having a subtle change in event handler ordering as mentioned in NEWS:

  The base scripts shipped with Zeek now use the ``established_connection_remove``
  event instead of ``connection_state_remove`` where possible
  (when the logic doesn't pertain to unestablished TCP connections).
  There's a performance benefit to this switch, but potentially breaks
  custom scripts that depended on accessing or modifying state via
  specific &priority ordering of ``connection_state_remove`` event handlers.
  Since most of Zeek's base scripts previously just used that event with
  the intention of writing a finalized log as the last thing executed
  for a given connection and the new ``established_connection_remove``
  event handlers all run after ``connection_state_remove``, it's not
  likely this change to the base scripts causes any incompatibility
  with user scripts.

- Grepping through Zeek packages, I didn't see anything obviously broken by the change.  However, the original idea (#642) of skipping ``connection_state_remove`` for unestablished TCP conns looked like it could have broke a couple (e.g. community ID plugin).

- One benefit of #642 would be that external user scripts automatically start participating in the performance improvement, but with this PR they'd need to change over to the new event.  I don't think that outweighs difference in potential breakages, but I'm now only slightly favoring this PR over the original.  Would like to hear what other impressions are.

- This PR still sees large performance improvements, similar to #642, for a million-SYN pcap.

- `zeek-docs` repo needs to be regenerated on merging (I didn't bother in case we pick a different event name)

### CODE REVIEW

**Comment by JustinAzoff** [comment]
This definitely makes the scan pcap a lot faster, but I wonder if it could  make traffic that is mostly non-scans slower.  Since it now raises 2 events on connection close where before it only raised one.

**Comment by jsiwek** [comment]
> This definitely makes the scan pcap a lot faster, but I wonder if it could make traffic that is mostly non-scans slower

The worst possible case for this PR is going to be if you had all traffic that was syn/syn-ack since then it's purely overhead of the additional event and not dwarfed by any further protocol parsing/analysis.  Even for that case, I don't see an issue:

[1m-synack.pcap.gz](https://github.com/zeek/zeek/files/3805848/1m-synack.pcap.gz)

* `topic/jsiwek/gh-646-conn-removal` average of 5 `zeek -C -r 1m-synack.pcap`: 57.124s
* `master` average of 5: 58.058s

The branch is possibly a bit faster because I removed one redundant "is there a connection_state_remove handler?" check that could have been adding up:

https://github.com/zeek/zeek/blob/e34562df4870eb0fc380f8e99b16f1d21a0fd472/src/Sessions.cc#L1050-L1051

Patching just that out of `master`, I get average of 57.478s

**Comment by vpax** [comment]
How about rather than "credible" (which I'm um definitely not a fan of!), "successful" (or, not as good IMHO, "productive")?  That takes care of the concern that "established" is a TCP-specific term.  Though for my druthers, I find "established" fits enough with the broader notion of "successful"/"productive" that it seems ok to me to use it for non-TCP

**Comment by jsiwek** [comment]
Main thing I wanted to avoid with `established_connection_remove` is confused symmetry with `connection_established`, which is a TCP-only event.  I'm cool using "established" if no one else thinks it's an issue.

"credible" was just from browsing thesaurus for alternatives; not a fan either :).  Other words that came up: "fruitful" or "effective".

Could also go with `connection_remove` for this.  None of the words so far describe what's going on too well anyway and maybe the terser name helps suggest "you probably want to use this one in most cases".

**Comment by 0xxon** [comment]
I still like ```established_connection_remove``` the best, even though I see that this could get a bit confusing with ```connection_established```. But - it conveys what it does best.

TI don't like credible or any of the alternatives. And - ```connection_remove``` seems like it might be quite confusing to someone who does not immediately look at the documentation - at least I could not guess what the difference to ```connection_state_remove```  would be.

**Comment by jsiwek** [comment]
Edited stuff and force-pushed to use `established_connection_remove`.

**Comment by rsmmr** [comment]
On the naming: ignoring the extension to UDP, is for TCP the meaningf of "established" here the same as with `connection_established`? I.e., a TCP connections triggers `established_connection_remove` if and only if it also had a `connection_established`? If yes, the naming sounds good to me; if no, I'd prefer a different name.

**Comment by jsiwek** [comment]
> ignoring the extension to UDP, is for TCP the meaningf of "established" here the same as with `connection_established`? I.e., a TCP connections triggers `established_connection_remove` if and only if it also had a `connection_established`?

No, not the same right now.

* `connection_established` isn't raised for "partial" connections and means something like "saw SYN from resp, but also only when orig has not already sent payload"
* `established_connection_remove` means anything except where we've only seen SYN(s) from orig and resp hasn't said anything

So one case where you get no `connection_established`, but do get `established_connection_remove` is if the initial handshake of a TCP conn gets dropped.

Can we align the meanings of "established" ?  Yes, but probably don't want to:

* Changing `connection_established` defeats a major point of this PR which was to avoid altering meaning of existing events.
* Changing `established_connection_remove` to exclude partial connections is moving away from the intended use-case which was to weed out just SYN scans.  Aligning it to same meaning as `connection_established` then starts weeding out more than that and becomes harder to reason about whether event handlers are still doing the right thing... seems that would then depend on whether a given analyzer handles partial connections (actually don't know we have any that do, but starting to feel excessively complex).

So sounds like choosing a different name is warranted.

How about `complete_connection_remove` ?  Using a new term like "complete" may help make sense of differences per transport proto: a "complete" UDP connection requires only 1 packet (unidirectional), but TCP requires resp to talk, too (bidirectional).

**Comment by rsmmr** [comment]
`completed_connection_remove`? I can also see the earlier suggestion `successful_connection_remove`. Or `full_connection_remove`? Naming is difficult. :)

**Comment by jsiwek** [comment]
Force pushed once again with the new name of `successful_connection_remove`.  Also added `connection_successful` event and a new `connection` field, "successful" to help indicate this new property.  Can consider this for review/merge again now (still need to generate docs on merge).

**Comment by rsmmr** [comment]
I like this, will review & merge shortly.

**Pull request merged**
