### PR TITLE
Add support for sending coverage data to Coveralls via Cirrus

### PR DESCRIPTION
**Pull request by timwoj**
This adds the ability for builds on `master` to send code coverage data to coveralls.io from cirrus.

Sample build: https://cirrus-ci.com/build/5493900158697472
Sample coveralls result: https://coveralls.io/builds/34366538

### CODE REVIEW

**Review by jsiwek — APPROVED** [review]
Nice, looks great to me if it were to get merged whenever and here's just minor questions/observations/suggestions:

* This will close #1116 or still something more to do there ?

* Files from `build/` won't be viewable in the web interface ?  Guess the obvious reason is that's since they're not committed to git, but wondered if there was any way to upload the source files along with the coverage results or if people would just have to generate coverage data locally if they wanted to look at those results more closely.

* Think it may be ok to generally exclude source files from `auxil/` projects in Zeek's coverage report.  i.e. if we aim to increase the testing coverage of auxilliary projects, it doesn't seem like the best way to do that is by adding tests from within Zeek.  Rather the project itself should extend its own test suite to increase coverage for itself and generate its own report.

**Comment by timwoj** [comment]
> This will close #1116 or still something more to do there ?

Yes, this should close #1116.

> Files from build/ won't be viewable in the web interface ?

I can take a look at the Coveralls API again, but the ruby gem I use to upload the data doesn't have any arguments for uploading files along side the data. I think what you said about someone just running the coverage locally if they want to look at those is fine.

> Think it may be ok to generally exclude source files from auxil/ projects in Zeek's coverage report. 

I already removed binpac and bifcl, which just left zeek-cut behind. I can remove it too. I agree that the individual projects should be responsible for their own coverage metrics.

**Comment by timwoj** [comment]
One remaining question is whether we want to link to this coverage data from somewhere. I'm not sure we even have documentation anywhere for running the coverage scripts manually.

**Comment by jsiwek** [comment]
> I already removed binpac and bifcl, which just left zeek-cut behind. I can remove it too.

I also saw broker and paraglob in the example report and say those can go, too.

> I'm not sure we even have documentation anywhere for running the coverage scripts manually.

`testing/coverage/README` is the first place I'd personally look if there's anything to update/extend there.  Or else the next place I might search for such a thing is the github wiki if you think its worth a page.

> One remaining question is whether we want to link to this coverage data from somewhere.

Like a linkable badge in the top-level README ?  No strong personal preference either way, but think it's maybe not that interesting to majority of people to have it so visible.  Maybe extending `testing/coverage/README` again to just have a link to where one can view the Coveralls report is sufficient.

**Pull request merged**
