### PR TITLE
Remove all 4.1 deprecations

### PR DESCRIPTION
**Pull request by timwoj**
This removes all of the deprecations that were marked to be removed in v4.1.

There's only one part I'm concerned about, which is the test changes f8bf9918fa21ef19e05ca5902ac057a7abaafee7. I removed one test entirely there, and the others I just need someone to take a close look at to make sure I didn't miss some coverage.

A branch with the same name needs to be merged in both the bifcl and docs repos when this one is merged.

### CODE REVIEW

**Comment by jsiwek** [comment]
Thanks.  One suggestion for possible followup: is the `ZEEK_FORWARD_DECLARE_NAMESPACED` macro a worthwhile indirection anymore?

**Comment by timwoj** [comment]
They can be removed but it's a fairly big change and felt out of scope for this PR. I can do it next week.

**Comment by ckreibich** [comment]
Guys we may have a problem with external plugin builds (like in Zeek packages) after this. Create a dummy plugin (`init-plugin` here is as included in master):
```
$ init-plugin foobar Foobar Foobar
Installing foobar/CHANGES ...
...
Initialized empty Git repository in /home/christian/t3/foobar/.git/
$ cd foobar
$ ./configure
...
```
Now build it:
```
$ cd build
$ make
Scanning dependencies of target bif-plugin-Foobar_Foobar-foobar.bif
...
[ 33%] Building CXX object CMakeFiles/Foobar-Foobar.linux-x86_64.dir/src/Plugin.cc.o
In file included from /home/christian/t3/foobar/src/Plugin.h:4,
                 from /home/christian/t3/foobar/src/Plugin.cc:2:
/home/christian/inst/opt/zeek/include/zeek/plugin/Plugin.h:5:10: fatal error: zeek-config.h: No such file or directory
    5 | #include "zeek-config.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Foobar-Foobar.linux-x86_64.dir/build.make:102: CMakeFiles/Foobar-Foobar.linux-x86_64.dir/src/Plugin.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:161: CMakeFiles/Foobar-Foobar.linux-x86_64.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```
Looks like `zeek-config --include_dir` now (intentionally) no longer lists the `zeek` subdirectory itself ...
```
$ zeek-config --include_dir
/home/christian/inst/opt/zeek/include:/usr/include:/usr/include:/usr/include:/usr/include:
```
... so while the plugin has `#include <zeek/plugin/Plugin.h>`, it in turn has a bare `#include "zeek-config.h"`, and nothing actually tells the compiler how to find `zeek-config.h`. Could it be that our own headers need a bit of nudging to include `zeek/`, or did I overlook something?

**Comment by jsiwek** [comment]
> Could it be that our own headers need a bit of nudging to include `zeek/`

@ckreibich yeah thanks, that should be it and if CI likes #1386, I'll merge that shortly

**Comment by ckreibich** [comment]
Awesome! Thanks Jon.

**Pull request merged**
