### PR TITLE
Removed deprecated list and timer types

### PR DESCRIPTION
**Pull request by karandeeppotato**
Removed the redundant list and timer types from the src dir.

But can't find any union type file in the `/zeek/src`.

### CODE REVIEW

**Comment by karandeeppotato** [comment]
OOPS!! Please ignore this pull request  ...I pushed the fix out without any checks

**Comment by timwoj** [comment]
Also, this issue is about the `list` and `timer` types in the scripting language, and not C++. 😃

**Comment by karandeeppotato** [comment]
Really sorry for the trouble but i didn't get the point...

Which file i have to remove.😅

**Comment by rsmmr** [comment]
It's not about removing files, this requires changes to the script interpreter to remove the code that implements `list` and `timer` types for the language.

**Comment by rsmmr** [comment]
I'll go ahead and close this.

**Pull request closed without merging**
