### PR TITLE
Fix HTTP evasion (Issue #1598)

### PR DESCRIPTION
**Pull request by jgvt**
- Happen when there is no CRLF at the end of HTTP message
    - Fix by adding CRLF when packet is complete (in relation to content-length in header)
    - Add weird log in this case
    - Adding corresponding btest

### CODE REVIEW

**Comment by jgvt** [comment]
Rework in progress

**Comment by jgvt** [comment]
Solve https://github.com/zeek/zeek/issues/1598

**Comment by 0xxon** [comment]
Thank you very much for the PR. It might get us a few days to get to this, as we are currently finishing up the next release. But - we have not forgotten about it :)

**Review by 0xxon — APPROVED** [review]
This actually looks pretty much perfect to me. There only are a few small indentation issues - and we can fix these while merging.

Thank you very much for adding a pcap and a new test - that is great.

Since I am not the most familiar with this code - would it would be great if either @timwoj or @rsmmr also could take a look before we merge this.

**Review by timwoj — APPROVED** [review]
I don't have a whole lot of experience in that area but it looks pretty straight-forward to me.

**Pull request merged**
