### PR TITLE
Bump Broker to pull in new Prometheus support and pass in Zeek's registry

### PR DESCRIPTION
**Pull request by ckreibich**
This is equivalent to https://github.com/zeek/zeek/tree/topic/neverlord/prometheus-cpp, except it doesn't change Zeek's handling of Prometheus and Broker always uses use the ZeekBundle approach, see [here](https://github.com/zeek/broker/compare/c47de11e4b84f24e8b501c3b1a446ad808e4964a...600a29ace5a962e76c8b8e1e03fa71cea0da738d#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR213-R220).

We can figure out how/whether to use the ZeekBundle approach more broadly in the 7.1 timeframe.

### CODE REVIEW

**Review by timwoj — CHANGES_REQUESTED** [review]
Can you re-enable the `scripts.base.frameworks.telemetry.internal-metrics` btest and ensure that it works as part of this?

**Comment by ckreibich** [comment]
D'oh yeah, I forgot. It needs some tweaking but looks promising. I'll iterate.

**Comment by ckreibich** [comment]
It's interesting — after the obvious data structure adaptations, I am seeing Broker's telemetry, but I just noticed that CAF;s is gone:

```
== Diff ===============================
--- /dev/fd/63  2024-07-11 02:09:10.453364176 +0000
+++ /dev/fd/62  2024-07-11 02:09:10.452364170 +0000
@@ -1,39 +1,27 @@
 ### broker |12|
-Telemetry::INT_GAUGE, broker, connections, [type], [native], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, broker, connections, [type], [web-socket], 0.0
-count_value, 0
-Telemetry::INT_COUNTER, broker, processed-messages, [type], [data], 0.0
-count_value, 0
-Telemetry::INT_COUNTER, broker, processed-messages, [type], [command], 0.0
-count_value, 0
-Telemetry::INT_COUNTER, broker, processed-messages, [type], [routing-update], 0.0
-count_value, 0
-Telemetry::INT_COUNTER, broker, processed-messages, [type], [ping], 0.0
-count_value, 0
-Telemetry::INT_COUNTER, broker, processed-messages, [type], [pong], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, broker, buffered-messages, [type], [data], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, broker, buffered-messages, [type], [command], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, broker, buffered-messages, [type], [routing-update], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, broker, buffered-messages, [type], [ping], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, broker, buffered-messages, [type], [pong], 0.0
-count_value, 0
-### caf |5|
-Telemetry::INT_COUNTER, caf.system, rejected-messages, [], [], 0.0
-count_value, 0
-Telemetry::INT_COUNTER, caf.system, processed-messages, [], [], 7.0
-count_value, 7
-Telemetry::INT_GAUGE, caf.system, running-actors, [], [], 2.0
-count_value, 2
-Telemetry::INT_GAUGE, caf.system, queued-messages, [], [], 0.0
-count_value, 0
-Telemetry::INT_GAUGE, caf.actor, mailbox-size, [name], [broker.core], 0.0
-count_value, 0
-### caf |2|
-Telemetry::DOUBLE_HISTOGRAM, caf.actor, processing-time, [0.00001, 0.0001, 0.0005, 0.001, 0.01, 0.1, 0.5, 1.0, 5.0, inf], [name], [broker.core]
-Telemetry::DOUBLE_HISTOGRAM, caf.actor, mailbox-time, [0.00001, 0.0001, 0.0005, 0.001, 0.01, 0.1, 0.5, 1.0, 5.0, inf], [name], [broker.core]
+Telemetry::COUNTER, broker, broker_processed_messages_total, [type], [pong], 0.0
+value, 0.0
+Telemetry::COUNTER, broker, broker_processed_messages_total, [type], [ping], 0.0
+value, 0.0
+Telemetry::COUNTER, broker, broker_processed_messages_total, [type], [routing-update], 0.0
+value, 0.0
+Telemetry::COUNTER, broker, broker_processed_messages_total, [type], [command], 0.0
+value, 0.0
+Telemetry::COUNTER, broker, broker_processed_messages_total, [type], [data], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_connections, [type], [web-socket], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_connections, [type], [native], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_buffered_messages, [type], [pong], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_buffered_messages, [type], [ping], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_buffered_messages, [type], [routing-update], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_buffered_messages, [type], [command], 0.0
+value, 0.0
+Telemetry::GAUGE, broker, broker_buffered_messages, [type], [data], 0.0
+value, 0.0
+### caf |0|
+### caf |0|
=======================================
```

@Neverlord, does that match your expectation? I could see either, but I couldn't quite tell — I see some mentioning of proxying between CAF's and Broker's registries. Help. :-)

**Comment by Neverlord** [comment]
> @Neverlord, does that match your expectation? I could see either, but I couldn't quite tell — I see some mentioning of proxying between CAF's and Broker's registries. Help. :-)

Where did you see a mention of that proxying? We have nothing of that sort. Unless prometheus-cpp has some clever API where we can tell it to pull in external metrics when scraped, we would have to mirror the metrics and periodically update them (i.e., poll), which would mean running some background thread for the task.

**Comment by ckreibich** [comment]
Thanks Dominik. It was just a bit of grepping, which led me to this:
```
2.4.0-dev.33 | 2022-08-02 20:06:17 +0200

  * telemetry: Introduce a broker::metrics_collector. (Arne Welzel, Corelight)

    - Add collect() on the registry and implement proxying between
      broker::telemetry and caf::telemetry via metrics_collector
```

**Review by timwoj — APPROVED** [review]

**Pull request merged**
