### PR TITLE
CI: Add Fedora 36, remove Fedora 34

### PR DESCRIPTION
**Pull request by 0xxon**
This should optimally also make it into 5.0.

### CODE REVIEW

**Comment by 0xxon** [comment]
I just noticed that these have interactions with a recent PR of Tim. Let me merge that and rebase these...

**Comment by 0xxon** [comment]
Test failure is legitimate and should not stop merging; see https://github.com/zeek/spicy/issues/1204

**Comment by 0xxon** [comment]
Also - this one should also optimally make it into 5.0.

**Comment by 0xxon** [comment]
Test failure is fixed in spicy main.

**Comment by timwoj** [comment]
Can you rebase this on master and push it so CI will retry?

**Comment by 0xxon** [comment]
done

**Pull request merged**
