### PR TITLE
VXLAN initial support

### PR DESCRIPTION
**Pull request by kramse**
Hi There

I am working on a patch and it seems I can decapsulate a few VXLAN packets, and get the inner packets processed. 

I am doing this PR to get guidance:
* Have I started in the right way, first patch to Bro
* What is required to make this a real patch, whats missing

I have a few things to add myself, but would like to get started.

### CODE REVIEW

**Comment by jsiwek** [comment]
Nice, thanks for the interest in starting this.  Here's some notes from my initial review:

- This seems generally like a good starting approach, the main thing to clean up is the VXLAN parsing code:
    - need to be more careful to avoid parsing past the end of
      available packet buffer (see protocol violations below)
    - generate potocol violations (and abort parsing)
      - "I" flag in VXLAN header must be set to 1
      - UDP length must have 8 + 14 bytes for VXLAN and inner ethernet header
      - inner ethertype must be IPv4 or IPv6
    - optional inner VLAN tag within ethernet frame isn't handled yet
    - ParseIPPacket needs to use either IPv4 or IPv6 depending on ethertype ?
    - could potentially seek to re-use existing iosource::Packet functions to even
      try to handle the the layer 2 (or also layer 3 ?) parsing (which should already handle VLAN tags)

 - outer UDP checksum of zero can be made acceptable for well-known VXLAN port (4789),
    so we don't always have to globally disable checksums (-C flag) to make VXLAN support
    work

- nice-to-have: an event that contains VNI and associated connection IDs (e.g. the unfinished vxlan_packet event)

 - final PR polish: I'd suggest squashing commits into a single one so:
    - we don't want to include the commit w/ the original 1 MB sample pcap
    - avoid unrelated whitespace or documentation changes (a separate PR for
      those is welcome), makes it less noisy to review and potentially easier for people
      to maintain isolated patches
    - if possible, run the existing unit test suite and update/fix any failures
      (if you're unsure of any, that's fine, I can help review/fix during merge)

**Comment by jsiwek** [comment]
Unless there's still near-term interest in finalizing this work, then I'm going to close this PR and instead open an issue that references back to it.

**Comment by kramse** [comment]
There is near term, starting from now and finish within this year. I have had some other tasks and travel.

**Comment by kramse** [comment]
Hi jsiwek and others, I did some updates and would kindly ask if you have any helpful hints for:
* Getting me up-to-date with the master, messed around with "init-bare.bro" to not have only white space changes
* Added VNI calculation but unsure how to get that over to the event

**Comment by jsiwek** [comment]
> * Getting me up-to-date with the master, messed around with "init-bare.bro" to not have only white space changes

I'm not too sure what all you had trouble with or what you tried, but maybe generally look around for Git tutorials related to terms "squash" and "rebase".  E.g. in your newer commits where you tried to remove the pcap, we'd still see a corresponding increase in the size of the Git repo because commits are always new objects, they never remove objects from older commits.  That's why we would want to actually revise the history of what commits are included in your branch before merging it into our repo's master branch.

Alternatively, if you're finding that way of fixing things up tricky, it may be easier to format out your current changes as a patch, start a new branch based on our latest master, and then re-apply your patch there (open a different PR).

> * Added VNI calculation but unsure how to get that over to the event

For a similar example, maybe see: https://github.com/zeek/zeek/blob/73ccc0f4acfabe9af66ec1fe48c8c63eb0849d89/src/analyzer/protocol/teredo/Teredo.cc#L204-L208

That is, you'll need to add a parameter for the VNI to the `vxlan_packet` event defined in events.bif and then generate that event at an appropriate place in the analyzer code.

**Comment by jsiwek** [comment]
I'm closing this due to inactivity, but leaving an open issue to reference it at https://github.com/zeek/zeek/issues/250.  Feel free to open a new PR later if more work/finalizations are done.

**Pull request closed without merging**
