### PR TITLE
Bump Spicy to latest release.

### PR DESCRIPTION
**Pull request by bbannier**

### CODE REVIEW

**Comment by bbannier** [comment]
This contains a Spicy bump for #2974.

**Review by awelzel — APPROVED** [review]
LGTM

**Comment by awelzel** [comment]
Hmm, there's quite some things in the bump. Maybe that should  bubble up into the Zeek NEWS file, even if it's just a one-lines.

Bumped Spicy to 1.5.4. Fixes GCC 13 compatibility and includes various performance and bug fixes. Link to the Spicy CHANGES?

```
14b9f0f9 Fix gcc-13 warnings about possibly dangling references.
eb488171 Silence gcc-13 warning for reproc.
9803a584 Add missing include for `uint64_t`.
461df272 Pin spicy-plugin to `release/1.3` for CI.
4b628187 Guard access to unit `_filters` member with feature flag.
702f83f8 Extend detection of conditionally used features in optimizer.
4ca157b8 Add support for folding ternary operator uses in optimizer.
39a5886c Cache HILTI C++ compilations with ccache in CI.
6c9cb5e4 Avoid expensive checked iterator for internal `Bytes` iteration.
e8112b93 Initialize `Bytes` internal control block for all constructors.
5d4ea45e Do not force locale on users of libhilti.
9408e44e Set reupload_on_changes for ccache caches.
28b27b66 Fix potential use-after-move bug.
71843491 Fix ASAN false positive with GCC.
dc695f9e Skip clang-specific ASAN flags with other compilers.
c1c46b52 Don't instantiate a debug logger if we aren't going to debug log.
819405d9 Simplify extract methods.
34cdd169 Shortcut some offset computations.
64971cc0 Apply alternative fix for #1345.
f3ddf63f Revert "Fix pathological performance for `_haveEod` on highly chunked streams."
dde4314a Make `printParserState` cheaper to call if debug logging is disabled.
327afa1e Use unique filename for all object files generated during JIT.
7a66703c Add stringification to UnitContext.
2f24b9fc Remove potential race during JIT when using `HILTI_CXX_COMPILER_LAUNCHER`.
```

**Comment by bbannier** [comment]
> Hmm, there's quite some things in the bump. Maybe that should bubble up into the Zeek NEWS file, even if it's just a one-lines.

Yes, that is exactly what has happened in the past.

**Comment by timwoj** [comment]
> Yes, that is exactly what has happened in the past.

Yeah, I usually get to it when I do the NEWS for a release.

**Comment by timwoj** [comment]
I'm not entirely sure why the docs generation failed. I ran the update while I was merging this PR and everything completed as expected here. If it happens after merging I'll give it another look.

**Pull request merged**
