### PR TITLE
Add missing implementation for threading_val_to_data

### PR DESCRIPTION
**Pull request by Neverlord**
The function `threading_val_to_data` in `threading/Data.h` had a prototype but no implementation until now.

I'm currently evaluating whether it's feasible in Zeek to drop the batching of log entries before handing them over to Broker. Instead of the batching and serializing, we could simply push each element to Broker as `broker::data` and let Broker do its job (CAF streams already use batches). It seems like the previous performance degradations that lead us to implement the batching on top of Broker no longer exist. Most likely as a result of switching to copy-on-write in Broker (https://github.com/actor-framework/actor-framework/pull/791). However, to push log entries from the manager directly, I need the `threading_val_to_data` functions.

This PR adds an implementation for that function as well as a unit test for it. All of Zeeks tests so far seem to center around the scripting interface. I hope I didn't miss something obvious, but I couldn't find a place to put my unit tests. And I'm very reluctant to contribute untested code. Hence, I've added the necessary scaffolding for the unit tests as well. 🙂

I can imagine adding the boilerplate code to enable C++ unit tests might lead to some controversy, so I'll try to to address potential concerns upfront:

- Currently, this is a one-off. However, having more fine-grained testing capabilities for C++ classes and functions directly will hopefully lead to more unit tests being added. I'm a big advocate for contributing new code always with accompanying  unit tests. Spending the extra hour two write unit tests and catch errors early often times safes many more hours of debugging later.
- The setup for testing C++ code is pretty much the same as in Broker.
- If you are concerned about the addition of the `test` module in `find_package(CAF ...)`: this part of CAF is header only and always available with the `core`. There are no extra link dependencies or other implications for `zeek` as a result.
- To avoid any additional build times or other side effects for Zeek users, the C++ unit tests are disabled by default. Users have to explicitly ask CMake (or the `configure` script) to build them.
- Adding all the testing boilerplate to `src/CMakeLists.txt` is suboptimal. I tried to put the CMake file under `testing/cpp/` at first, but to get `zeek-test` to built I had to add all the dependencies of `zeek` because not everything is nicely wrapped into static libraries like `brokercomm` to allow re-using dependencies someplace else. Maybe there's still a better way to do it, though.
- Zeek has lots of global state and functions referenced by its submodules in `main.cc`. I had to copy a large portion of `main.cc` into `zeek-test.cc` as a result to make the linker happy. I'm sure there are many unnecessary includes etc. in `zeek-test.cc`, but tracking those down didn't seem worthwhile.

### CODE REVIEW

**Comment by jsiwek** [comment]
I had recently talked to Tim/Johanna a bit about our need to start doing real C++ unit tests and already planned to bring that topic up to the wider group, so I think it's great to have the help in getting that infrastructure started.

Main thing would be to check if everyone's ok using CAF as the unit testing framework or have other suggestions (I don't have any myself).  i.e. best if we pick a framework that satisfies all requirements rather than switch later on (but can't really imagine anything CAF doesn't/couldn't support).

For this particular PR's addition of `threading_val_to_data`, a minor suggestion is that I'd rather see that get merged along with a feature that makes use of it, else it feels like merging potentially dead code.  So depending on how the general discussion around CAF unit-testing goes, I'd either hold off on merging this until it goes along with your batching changes, or would rather the unit-testing part of this PR got separated out (maybe can instead add a few example tests for some simple "util" functions instead).

**Comment by rsmmr** [comment]
Thanks for getting the unit testing started, @Neverlord . Thoughts:

- Main question seems indeed the framework. I don't have strong feelings any particular way. It seems worth a bit of discussion of what our options are (CAF is certainly a good one, as we already use it; catch2 is pretty common; and I was looking at doctest the other day, which seems interesting). Might be best to move the discussion to zeek-dev with some requirements and pros/cons.

- I'd also split this out from the `threading_val_to_data` change. As you're still testing that side anyways. Ideally the timing will work out to merge the unit testing scaffold first, and then the feature.

- The `zeek-test.cc` is a bit unfortunate indeed. Seems we could at least factor out the includes & globals and then pull that in from both main and test?

- No need for the configure option I would say; if we're already start having unit tests, then we should also always build & run them

**Comment by jsiwek** [comment]
> * No need for the configure option I would say; if we're already start having unit tests, then we should also always build & run them

I like having the option to enable/disable tests.  Not too sure what default to use, but lean toward disabled since the people who most often run tests (developers) might be the minority of all people that compile (regular users or packagers), so want to avoid making build times longer for most people who aren't even interested.

Obviously making a couple assumptions there, but even assuming wrongly, seems Less Bad to make devs explicitly enable tests than it is to increase build times for even just a few users that won't ever bother running tests.

**Comment by 0xxon** [comment]
> I like having the option to enable/disable tests. 

Same here.

**Comment by timwoj** [comment]
Catching up on this thread.

> Zeek has lots of global state and functions referenced by its submodules in main.cc

The large amount of global state is something I'd really like to fix in the future. It's a bit obnoxious to have to grep to figure out where a function is defined/used all the time. I totally understand that making changes to that is fraught with danger though.

> Main question seems indeed the framework. I don't have strong feelings any particular way.

Same. I have the most experience with googletest. Catch2 looks nice being single-header and a good license, or CAF since we already have it.

> How much of a build time increase are we talking about here? That can't be that much, no?

That depends on the tests and how complicated they are, I'd suspect. Most of the people who are going to run unit tests are in a minority of the users who build zeek from scratch. Assuming the unit tests are just for internals (since we have btest for wider tests), it's just the people doing active development. Even people doing things like plugins probably wouldn't run the unit tests. Either way, having a flag to turn them on/off is ideal.

**Comment by jsiwek** [comment]
> How much of a build time increase are we talking about here? That can't be that much, no?

Hard to know ahead of time.  It's also not fixed and expect it to continuously grow over time rather than shrink, but imagining a world where we had tests to cover every branch of Zeek seems like a significant amount of extra build time that's wasted effort for most users.

That's at least the long-term theory, but a pragmatic short-term approach is to enable tests by default and wait to see if build times are significantly impacted later on and/or whether we get complaints.  Can always change to disabled by default later.

**Comment by Neverlord** [comment]
> For this particular PR's addition of `threading_val_to_data`, a minor suggestion is that I'd rather see that get merged along with a feature that makes use of it

ACK. I thought it a good idea to add missing API pieces now, since removing the Zeek-side batching of Broker messages is going to be a bigger change. Separating out intermediate steps makes the "final PR" smaller, but of course you're right in that if we don't end up removing the batching (or do in a different way than I'm currently working on) than the intermediate PRs just end up introducing dead code. Didn't think that through. 🤔

> How much of a build time increase are we talking about here? That can't be that much, no?

Initially it's not adding much. However, as Jon points out: the more test suites we add the longer the build time becomes. As a reference, compiling CAF with and without testing (129 test suites currently) is a big difference in build time.

> I'd either hold off on merging this until it goes along with your batching changes, or would rather the unit-testing part of this PR got separated out (maybe can instead add a few example tests for some simple "util" functions instead).

I'll happily separate out the unit testing scaffold if you wish.

> Same. I have the most experience with googletest. Catch2 looks nice being single-header and a good license, or CAF since we already have it.

For basic `CHECK` and `REQUIRE` tests with fixtures, I think Catch2, googletest, Boost.Test, etc. are all pretty interchangeable. One thing that may speak for using CAF's testing headers (aside from Zeek having already access to it) is that it allows deterministic testing of actors in case Zeek ever decides to parallelize some tasks / components with actors.

> The `zeek-test.cc` is a bit unfortunate indeed. Seems we could at least factor out the includes & globals and then pull that in from both main and test?

Probably the cleanest solution would be to provide one extra `.cc` file (`globals.cc`?) that bundles all global functions and variables. In that case we wouldn't even have to include a single Zeek header into `zeek-test.cc` since the linker finds all the symbols it needs from that other `.cc` file.

@jsiwek what do you think is the best way forward? Close this PR, discuss/agree on unit testing setup, and then add the test scaffold separately in a new PR? (plus include `threading_val_to_data` in the final PR that actually uses the code.)

**Comment by jsiwek** [comment]
I opened #643 to get the unit test infrastructure sorted out separately there.  Can plan to include the `threading_val_to_data` changes along with the batching optimization.  Or if you find any other beneficial changes that are independent of even that, PR those anytime (e.g. maybe https://github.com/zeek/zeek/pull/633/commits/30a82365cd507e93466f8f02246d6c8f9be847b0)

**Pull request closed without merging**
